### ISSUE TITLE
Grafiken / Icons

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#10]
Nach intensiver Beratung mit einer 18-jährigen schlage ich vor, dass wir nur noch Lektions-Icons verwenden, also pro Lektion ein Icon, das dann auf jeder Seite der Lektion auftaucht, an immer der gleichen Stelle.

Horizontal: Rechtsbündig mit dem rechten Ende der Breadcrum-Leiste
Vertikal: Zwischen Titel und Überschrift

Können wir die Free Icons des [Awesome Fonts](https://fontawesome.com/icons?d=gallery&p=2&m=free) dafür verwenden und ggf. die Farben ändern? Oder sollen wir anderen nehmen?

**Comment by BITS-Editor** [comment]
Für mich:
- zu groß
- zu blass/transparent

**Comment by andi-blafasl** [comment]
Auch hier ein neuer Versuch:
https://bits-training.github.io/030-lektion-e-mail/ <- Hier ist das Logo jetzt etwas kleiner, dafür aber in der Farbe der Überschriften. So als versuch eine bestehende Farbe des Themes wieder aufzugreifen. Vorher war es die Farbe der Breadcrum-Box oben.
https://bits-training.github.io/030-lektion-e-mail/01.was-sind-emails/ <- Hier ist das Logo nochmal etwas kleiner, die Farbe ist etwas heller als die Überschriften.

Das ganze ist auch schon dynamisch abhängig von der Arte der Seite. Das erste Beispiel ist eine List-Page, das andere eine Single-Page.

also nochmal Feedback bitte ;-)

**Comment by BITS-Editor** [comment]
Mir gefällt Deine erste Variante mit dem dunkleren Logo ganz gut.

**Comment by andi-blafasl** [comment]
> Mir gefällt Deine erste Variante mit dem dunkleren Logo ganz gut.

Meine Idee war das man für die Übersichtseite (in Hugo List-Page genannt) ein auffälligeres Logo nimmt und dann auf den Seiten mit Text (in Hugo Single-Page genannt) ein unauffälligeres Logo verwendet damit es nicht vom eigentlichen Text ablenkt.
 
> Allerdings ist jetzt auf jeder Seite links oben ein Briefumschlag 👎🏼 :-)

:man_facepalming: Ich hab das ja auch erst mal ziemlich simple implementiert...
ich wollte nicht so viel Zeit investieren für die Demo. Wäre ja umsonst gewesen wenn es dir nicht gefallen hätte 😜 

Jetzt hab ich es über einen Parameter im Front-Matter konfigurierbar gemacht. Wenn es einen Parameter in aktuellen Seite gibt, wird der verwendet, ansonsten wird der Parameter aus der _index.md genommen. Und wenn es da auch keinen Parameter gibt, dann ist das Icon weg. Technisch würde ich sagen ist das jetzt sehr gut gelöst, jetzt muss es nur noch optisch angepasst werden. 👍

**Comment by BITS-Editor** [comment]
Ich bin mir immer noch unsicher, ob wir die Icons überhaupt platzieren. Der Platz ist in meinen Augen nicht ideal - aber einen besseren sehe ich auch nicht. WENN wir Icons nehmen, würde ich sie schon immer pro Lektion einheitlich machen, also nicht die Startseite von den Unterseiten unterscheiden.

Eine alternative Position wäre in der gleichen Zeile wie die Überschrift und dann linksbündig. Könntest Du das versuchen einzurichten?

Tut mir leid, dass ich hier so rumeiere.

**Comment by BITS-Editor** [comment]
Lutz: Icons aus https://fontawesome.com/icons?d=gallery&p=2&m=free für die Lektionen raussuchen und in die jeweilige index-Datei im Header einfügen.

**Comment by BITS-Editor** [comment]
Ich habe die Lektionen E-Mail und Virus mit icons in allen Headern ergänzt/aktualisiert, aber in Virus werde diese nicht angezeigt.

**Comment by andi-blafasl** [comment]
Der Virus war zu neu für das LearnTheme. Ich hab die Font Awesome Schrift aktualisiert, jetzt wird er angezeigt.

**Comment by BITS-Editor** [comment]
Verrückt, in der https://bits-training.github.io/ wird das Icon bei Virus angezeigt - bei meiner lokalen Installation trotz Pull nicht. Welche Datei hattest Du angepasst? Dann kann ich mal auf das Änderungsdatum bei mir gucken.

**Comment by andi-blafasl** [comment]
https://github.com/BITS-Training/BITS-hugo/commit/2a326f6aa5228aa5dde8a2807766306cb12097f9

**Comment by BITS-Editor** [comment]
1. Virus-Icon wird jetzt angezeigt. Danke!

2. Manchmal ragt die Überschrift in das Icon. Kann man die Icons ggf. kleiner machen? Hängt natürlich von der Bildschirmauflösung ab.

**Comment by andi-blafasl** [comment]
Ich konnte dein Problem mit dem Virus-Icon reproduzieren. Da hilft im Browser ein STRG+F5 um den Cache für die Seite komplett ohne Cache neu zu laden.

Das Icon könnt man via CSS-Media-Queries abhängig von der Auflösung kleiner machen. Muss ich testen ob das einfach geht.
