### ISSUE TITLE
Quizdown Syntax strikt beachten!

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#102]
Der Syntax muss strikt eingehalten werden. Sie [Issue #21](https://github.com/bonartm/quizdown-js/issues/21) bei quizdown.js

Falls in neuerer Version behoben, dann diese wieder hier einbauen.

**Comment by andi-blafasl** [comment]
Auch in Quizdown 0.6.0 ist der Bug noch vorhanden.
Da es kein wirkliches Problem ist, neh ich den issue aus dem milestone.

**Comment by BITS-Editor** [comment]
Verschoben in Milestone Version 7.

**Comment by andi-blafasl** [comment]
Es gibt ja leider beim quizdown keine wirkliche Weiterentwicklung und es funktioniert ja grundsätzlich. Wenn wir eine neue Version machen, dann check ich auch immer die aktuelle Version des quizdown Scripts. Damit schließ ich das issue hier.
