### ISSUE TITLE
Nutzungsanalyse von BITS

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#103]
GoatCounter und Matomo einbinden. Konfigurierbar über Variablen in der config.toml

Siehe Branch [goatcounter](https://github.com/BITS-Training/BITS-hugo/tree/goatcounter)

**Comment by BITS-Editor** [comment]
Über https://hanadigital.github.io/grev/?user=BITS-Editor&repo=BITS-hugo kann man die Downloads der Releases zählen lassen.

**Comment by BITS-Editor** [comment]
In den Branches https://github.com/BITS-Training/BITS-hugo/tree/develop und https://github.com/BITS-Training/BITS-hugo/tree/goatcounter ist in den Config-Dateien alles für eine lokale Nutzung von [Goatcounter](https://www.goatcounter.com) und [Matomo](https://matomo.org) zum Zählen von lokalen Aufrufen eingebunden. Beide Services sind datenschutzfreundlich und Open Source.

**Comment by andi-blafasl** [comment]
Integration ist eingebaut und funktioniert. Auf der Demo-Seite werden beiden Techniken aktiv genutzt.

**Comment by BITS-Editor** [comment]
Bitte noch in /static/read.me ergänzen, was wo dafür konfiguriert werden muss.

**Comment by andi-blafasl** [comment]
Hab den Absatz entsprechend angepasst.

**Comment by BITS-Editor** [comment]
Super, danke!
