### ISSUE TITLE
Verbesserungsvorschlag Kapitel Kennwörter

### ISSUE THREAD

**Issue by hagen-bauer-rc** [BITS-Training/BITS-hugo#104]
Das BSI gibt Empfehlungen für sichere Kennwörter. Gibt es einen Grund, warum diese nicht ganz übernommen werden? Mir fehlt vor allem die MFA und der Passwortmanager.

https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Accountschutz/Sichere-Passwoerter-erstellen/sichere-passwoerter-erstellen_node.html

Vielleicht könnte man auch das vom BSI Video direkt integrieren?

**Comment by BITS-Editor** [comment]
Vielen Dank für den Hinweis! Hier gibt es sicher noch Verbesserungsbedarf.

MFA und Passwortmanager möchte ich allerdings nicht empfehlen, da in den Behörden dann gleich die Frage der Beschäftigten nach entsprechenden Tools kommt und außerdem MFA keine Entscheidung der Beschäftigten ist, sondern der IT. Was soll ich als Beschäftigter mit dem Hinweis auf MFA anfangen, wenn mein Dienstherr das nicht unterstützt?

Welche weiteren Verbesserungen könnten wir noch prüfen? Sicher den Hinweis, Passwörter nicht mehrfach zu verwenden.

**Comment by hagen-bauer-rc** [comment]
Es wird ja an verschiedenen Stellen auch der "Privatmensch" in der Organisation angesprochen. Man könnte ja MfA / Passwortmanager für die private Nutzung empfehlen und/oder einen Hinweis "fragen Sie Ihren Ansprechpartner" einfügen.

**Comment by andi-blafasl** [comment]
Je mehr Benutzer Techniken wie Passwortmanager und MfA kennen, um so eher werden Sie bei Betreibern auch nachgefragt. Grundsätzlich finde ich die Idee das zu erwähnen schon gut. In welchem Umfang, ist natürlich die andere Sache.

**Comment by BITS-Editor** [comment]
Das Kapitel ist im Branch https://github.com/BITS-Training/BITS-hugo/tree/develop und es gibt eine neue Seite zu Passwort-Managern und 2FA. Bitte prüfen, danke!

**Comment by BITS-Editor** [comment]
Überarbeitet.

**Comment by hagen-bauer-rc** [comment]
sieht gut aus
