### ISSUE TITLE
Theme Update

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#105]
Es gibt ein aktualisiertes Release vom relearn theme mit Bugfixes.
Ich hab dafür einen Branch update-theme angelegt. Bitte testen. Wäre für das nächste BITS Release interessant.

@BITS-Editor denk nach dem checkout an den "git submodule update --init --recursiv" :wink:

**Comment by BITS-Editor** [comment]
Danke! Schaue ich mir an, ggf. dauert das aber.

**Comment by BITS-Editor** [comment]
Soweit ich das erkenne, wurde in der 2.9.6 nur ein Bug hinsichtlich der Pfeilnavigation gefixt. Diese funktioniert bei uns, auch sonst konnte ich keine Fehler feststellen.

Wie wollen wir mit weiteren Updates des Relearn themes umgehen? Ich denke, dass wir, wenn wir bei uns keine Fehler feststellen, nicht alleine wegen eines Updates ein neues Release von BITS erstellen sollten. Es gibt ja seit der 2.9.6 schon diverse weitere Updates und einen Wechsel zur v3.

Ich würde bei einem aus anderen Gründen geplanten Release von BITS dann die neueste Version von Relearn übernehmen bzw. testen. Wäre das OK?

**Comment by andi-blafasl** [comment]
Ja, ich würde auch nur bei einer Aktualisierung von BITS auf ein Update vom Theme schauen, oder eben wenn es Probleme gibt und die Upstream evtl. gefixed sind. Nur wegen einem neuen Theme machen wir kein neues BITS release.

**Comment by andi-blafasl** [comment]
Ok, die 3.0.0 hab ich noch garn nicht bemerkt. :wink:
Was ich gerade gesehen hab: bei der [2.9.0](https://mcshelby.github.io/hugo-theme-relearn/basics/migration/#290) gab es wohl einen breaking-Change mit _ref/relref_ und das nutzen wir doch auch im content. Müssen wir noch testen oder hast du schon gesehen das es funktioniert?

**Comment by BITS-Editor** [comment]
Ich habe nur die Seiten(pfeil)navigation und die Menünavigation getestet. Was müsste ich noch für die 2.9.0 testen?

**Comment by andi-blafasl** [comment]
Die aktuelle Version is im Branch [update-theme](https://github.com/bits-training/bits-hugo/tree/update-theme) eingepflegt.

Es gibt jetzt auch einen Dark-Mode des default Themes, falls wir das übernehmen wollen ;-)

Know-Issues:
- https://github.com/McShelby/hugo-theme-relearn/issues/275

**Comment by andi-blafasl** [comment]
Demo unter https://bits-training.github.io/training/index.html online

**Comment by andi-blafasl** [comment]
Header-Icon bei den Lektionsseiten wieder an den Rand

**Comment by BITS-Editor** [comment]
Theme Update 4.1.0 sieht grundsätzlich gut aus, bis auf zwei Punkte. Ich habe die Release-Notes der Änderungen ab 3.0 überflogen und https://bits-training.github.io/training/index.html getestet.

1) z.B. unter https://bits-training.github.io/training/200-ansprechpersonen/ ragt die Überschrift in das Icon rein. Offenbar ist das noch nicht weit genug entfernt wie in der früheren Version. Andere Seiten sind auch betroffen, z.B. https://bits-training.github.io/training/110-lektion-mein-arbeitsplatz/05.vorsicht-bei-mobilen-datentraegern/
2) schon in den früheren Versionen, aber auch in 4.1.0 gibt es auf der Ergebnis-Seite des Quiz offenbar keine Möglichkeit, per Tastatur die Fragen auszuwählen und die Links zu aktivieren. Dazu habe ich eine Issue beim Quiz-Repo unter https://github.com/bonartm/quizdown-js/issues/27 eröffnet. Dieses Problem habe ich auch in #79 ergänzt.

**Comment by andi-blafasl** [comment]
Theme auf Version 5.2.3 aktualisiert. Damit auch das Icon oben rechts neu implementiert, das sollte Punkt 1 beheben.

Die Navigations-Pfeile sind jetzt oben in der Brotkrumen-Leiste über FontAwesome Icons realisiert, ohne CSS gibt's die nicht.

Die beiden Dropdown-Boxen sind im Theme für die Sprach-Auswahl und eine für eine Design-Variante. Das wird im Normalzustand über CSS ausgeblendet wenn deaktiviert, aber der HTML-Code wird immer generiert. Lässt sich nicht abschalten. Ich würde die Design-Variante für die Barriere-Armut empfehlen. Dann kann man ein "High-Kontrast" Theme machen und einen Dark-Mode 😉

**Comment by BITS-Editor** [comment]
Ok. 

Nur ein Punkt fällt mir hier dann noch auf: Auf der Lektionseinstiegsseite ist das Icon deutlich näher in der Mitte auf den Unterseiten. Kann man das noch vereinheitlichen, also am besten so wie auf den Unterseiten darstellen?

**Comment by andi-blafasl** [comment]
Das ist leider nicht so einfach möglich. Da die Lektions-Startseiten nutzen einen komplett anderen Aufbau der Überschrift. Das Icon wird aber immer auf die selbe weise eingebunden. Und damit sieht es unterschiedlich aus. Meiner Meinung nach ist das OK so, da es auf den Startseiten prominenter platziert sein soll.

**Comment by andi-blafasl** [comment]
Achso, das Icon ist immer an der gleiche stelle: Rechts am Rand des Textkörpers. Der Textkörper ist bei den Startseiten deutlich schmaler und deshalb geht das Icon wirklich nicht weiter nach rechts. In der alten Version war das Icon ziemlich schlecht an den rechten Rand der Seite gepfuscht. Deshalb kam es da auch zu diesen Überlappungen und so. Das ist bei der neuen Variante halt sauber im Layout integriert und deshalb an der neuen Stelle. Ich bekomm das nur so hin das es beim ändern der Browser-Breite sauber funktioniert.

**Comment by BITS-Editor** [comment]
Ok. Ab dafür.

**Comment by BITS-Editor** [comment]
Die 5.3.0 ist da.

https://github.com/McShelby/hugo-theme-relearn/releases/tag/5.3.0 und hat das Issue #307 umgesetzt.

Wir können daher mE jetzt das übernehmen und die Beta der v6.2 erstellen.

**Comment by andi-blafasl** [comment]
done
