### ISSUE TITLE
Quiz-Frage zu USB-Sticks

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#106]
Die erste Quiz-Frage ist kritisch, da USB-Sticks generell ein Problem darstellen. Die Frage sollte überarbeitet werden.
https://bits-training.de/training/100-lektion-mobile-geraete/90.quiz-mobile-geraete/

**Comment by BITS-Editor** [comment]
Die Quiz-Frage ist im Branch https://github.com/BITS-Training/BITS-hugo/tree/develop überarbeitet.

**Comment by BITS-Editor** [comment]
@hagen-bauer-rc : Vielleicht wollen Sie hier einen Blick drauf werfen? Danke!

**Comment by BITS-Editor** [comment]
Nochmal überarbeitet.

**Comment by hagen-bauer-rc** [comment]
Hallo, entschuldigen Sie die späte Rückmeldung.  Vielleicht verweisen wir noch auf eine mögliche Richtlinie zum Umgang mit mobilen Datenträgern. 

 " Prüfen Sie ob eine Richtlinie für den richtigen Umgang mit Wechseldatenträgern vorhanden ist. Hier sollte unter anderem festgelegt worden sein, welche Wechseldatenträger genutzt werden und wer diese einsetzen darf und  mit welchen externen Mitarbeitern oder Dienstleistern Datenträger ausgetauscht werden dürfen und welche Sicherheitsregelungen dabei zu beachten sind"

**Comment by BITS-Editor** [comment]
@hagen-bauer-rc : Vielen Dank!

Ich habe in die Zusammenfassung eine Notiz zu einer möglichen Richtlinie aufgenommen - da passt der Hinweis meines Erachtens besser als im Quiz.
![image](https://user-images.githubusercontent.com/7092938/189112513-07c4629b-b452-4c1b-b8a3-1c4002836380.png)
