### ISSUE TITLE
Barrierearmut - Kontraste Suchbox

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#108]
1. Rahmen um Suchfeld dunkelgrau machen
2. "Suchen" im Suchfeld mit stärkerem Kontrast färben
3. Hintergrund des Suchfelds in weiß ändern
4. Such-Icon farbig machen

**Comment by BITS-Editor** [comment]
@andi-blafasl prüft das.

**Comment by BITS-Editor** [comment]
In der Datei theme-bits.css unter static/css habe ich bei 
1. --MENU-SEARCH-BOX-color: den Wert von #404040 auf #33a1ff geändert
2. --MENU-SEARCH-BOX-ICONS-color: den Wert von #a1d2fd* auf #064479 geändert
3. --MENU-SEARCH-BG-color: den Wert von  #167ad0 auf #ffffff geändert
4. --MENU-SEARCH-BOX-ICONS-color: den Wert von #a1d2fd* auf #064479 geändert

**Comment by andi-blafasl** [comment]
über den Kontrast beschwert sich das WAVE-Tools gar nicht. Ich würde vorschlagen wir besprechen das Thema mit den Kontrasten wenn die Erklärung für Barrierearmut machen lassen. Ich glaub dem Tools nämlich nicht mehr.

**Comment by BITS-Editor** [comment]
Diese Hinweise stammen NICHT vom Wave-Tool, sondern von der Hochschule in Bremen. Bitte nochmal prüfen, vielleicht ist meine Lösung ja gut.

**Comment by andi-blafasl** [comment]
Ist im High Contrast Theme so ähnlich umgesetzt. die Variablen haben sich bei der aktuellen Theme-Version geändert.
