### ISSUE TITLE
Voreinstellung der Suche

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#11]
Laut Andreas funktioniert die Suche nur, wenn die Seite auf einem Web-Server liegen. Wenn dem so ist, würde ich sie standardmäßig abschalten und in der Readme die Aktivierung und die Voraussetzungen dafür beschreiben.

**Comment by andi-blafasl** [comment]
Wenn du die Standard-Version für direkten Dateizugriff ohne Webserver einstellen willst, dann gehen auch die Verlaufs-Haken nicht. Vielleicht bieten wir einfach beide Versionen zum Download an? Dann muss sich ein Interessent nicht mit dem erstellen beschäftigen und hat beide Versionen direkt im Zugriff. Das erstellen geht eventuell ganz einfach über eine Config-Directory so wie hier https://gohugo.io/getting-started/configuration/#configuration-directory beschrieben.
Vorerst würde ich mich auf die Version für Webserver konzentrieren, wenn die komplett funktioniert ist das Abschalten der Suche und der Haken ja das einfachste.

**Comment by BITS-Editor** [comment]
Ok, machen wir so. Mit den Haken hatte ich vergessen. Das hätte ich ja schon gerne :-)

**Comment by andi-blafasl** [comment]
mit Commit https://github.com/BITS-Training/BITS-hugo/commit/713d3d8c0cec69bc66a4b2b1aafb1de289602e1c erledigt
