### ISSUE TITLE
create-release.bat unklar dokumentiert

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#110]
Wenn man die create-release.bat auf aufruft, wir man aufgefordert einen TAG zu vergeben - mehr kann man nicht machen. Der Umgang mit der Batch-Datei sollte erläutert werden.

**Comment by andi-blafasl** [comment]
Das ist nur eine kleine Hilfsdatei für mich die mir das erstellen der ZIP-Dateien bei einem Release erleichtert. Die braucht sonst niemand und eigentlich könnte/müsste ich das über GitHub Actions regeln...

**Comment by BITS-Editor** [comment]
OK. Falls sie drin bleibt, sollten wir in der readme darauf hinweisen.

**Comment by andi-blafasl** [comment]
steht jetzt in der README
