### ISSUE TITLE
Barrierearmut - Kontrast "Notice"

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#112]
Gemäß der FF-Erweiterung "WCAG - Contrast checker" ist bei den "Notices" der Kontrast nicht ausreichend. Hier müssten wohl anderen Hintergrundfarben gewählt werden.

**Comment by BITS-Editor** [comment]
@andi-blafasl prüft das.

**Comment by BITS-Editor** [comment]
Die Änderungen müssen anscheinend in theme/hugo-theme-relearn/static/css/theme.css unter
div.notices.note {
    border-color: #BF8B44;
    background-color: #FFF2DB;

und
div.notices.tip {
    border-color: #5AA55A;
    background-color: #E6F9E6;

vorgenommen werden.

**Comment by BITS-Editor** [comment]
Ich habe den Wert für notices.note geändert. Leider sind meine Kontrast-Tools nicht aussagefähig, ob das genügt.

**Comment by andi-blafasl** [comment]
Auch hier würde ich die Meinung von den Experten abwarten. So dunkel wie man das laut WAVE-Tool machen muss, da können wir gleich schwarz/weiß machen...
![image](https://user-images.githubusercontent.com/3586675/193329569-aced9779-bccc-47a7-860f-e324b6b78477.png)

so ist das deutlich schöner:
![image](https://user-images.githubusercontent.com/3586675/193330725-34468b89-01e8-48ba-9783-574a68ec354d.png)

Ich denke auch, es ist wichtiger eine schöne Farbe bei der Box zu verwenden ist wichtiger als ob jemand mit Kontrastproblemen das "Achtung" gut lesen kann. Der wichtige Inhalt in der Box hat ja ein passendes Kontrastverhältnis.

**Comment by BITS-Editor** [comment]
Mit der neuen Kontrast-Auswahl ist das Problem vielleicht gelöst. Wir warten mal die Prüfung bei der Erklärung zur Barrierefreiheit ab.
