### ISSUE TITLE
HTML-Fehler gemäß Validator.nu

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#114]
Der HTML-Validator gibt Fehler und Warnungen zu HTML aus:
1. https://validator.nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fbits-training.de%2Ftraining%2F020-einleitung%2F
2. https://validator.nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fbits-training.de%2Ftraining%2F030-lektion-e-mail%2F

Die Ergebnisse zu 1. sind wohl fast überall in BITS zu finden.

**Comment by andi-blafasl** [comment]
die Fehler sind im Validator auch mit aktueller Theme-Version vorhanden. Scheinen aber keine Auswirkung auf die Seite im Browser zu haben. Mal sehen was mcShelby dazu sagt: https://github.com/McShelby/hugo-theme-relearn/issues/329

**Comment by andi-blafasl** [comment]
die Fehler sind "kosmetisch" und können ignoriert werden.
