### ISSUE TITLE
E-Mail/Computerviren: unvollständiger Satz

### ISSUE THREAD

**Issue by maffe** [BITS-Training/BITS-hugo#116]
https://github.com/BITS-Training/BITS-hugo/blob/22f37dd5e27e26bf3f6f81e481711db98a773d1f/content/030%20lektion%20e-mail/04.Computerviren.de.md?plain=1#L29
Der Punkt endet mit `, und`, es folgt aber kein weiterer Inhalt.

**Comment by BITS-Editor** [comment]
Danke, fixe ich gleich.
