### ISSUE TITLE
Schreibweise Netiquette

### ISSUE THREAD

**Issue by maffe** [BITS-Training/BITS-hugo#120]
Überwiegend wird „Net(t)ikette“ benutzt, z. B. hier:
https://github.com/BITS-Training/BITS-hugo/blob/22f37dd5e27e26bf3f6f81e481711db98a773d1f/content/030%20lektion%20e-mail/10.Net-t-ikette.de.md?plain=1#L2
Üblicher scheint aber die Schreibweise Netiquette zu sein.

Zumindest sollte folgender Ausreißer geändert werden:
https://github.com/BITS-Training/BITS-hugo/blob/22f37dd5e27e26bf3f6f81e481711db98a773d1f/content/030%20lektion%20e-mail/11.Zusammenfassung.de.md?plain=1#L18

**Comment by BITS-Editor** [comment]
Laut Duden ist es wohl die "Netiquette". Ich ändere dann auf dieses Wort. Danke!

**Comment by BITS-Editor** [comment]
Geändert in [BITS-hugo/content/030 lektion e-mail/10.Net-t-ikette.de.md](https://github.com/BITS-Training/BITS-hugo/blob/22f37dd5e27e26bf3f6f81e481711db98a773d1f/content/030%20lektion%20e-mail/10.Net-t-ikette.de.md) und [BITS-hugo/content/030 lektion e-mail/](https://github.com/BITS-Training/BITS-hugo/blob/main/content/030%20lektion%20e-mail/10.Net-t-ikette.de.md); allerdings mit Änderung des Dateinamens in 10,Netiquette.de.md
