### ISSUE TITLE
Dark & High Constrast Theme

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#127]
Ein eigenes Theme für die Barrierefreiheit und für die Dark-Mode Fans.

https://github.com/BITS-Training/BITS-hugo/tree/highcontrast-theme

**Comment by BITS-Editor** [comment]
Sehr schön, gefällt mir gut!

Ich würde das übernehmen.  Allerdings habe ich noch eine Bitte zur Benennung:
- Normaler Kontrast
- Hoher Kontrast
- Dunkles Theme

Danke!

**Comment by andi-blafasl** [comment]
Die Bezeichnungen setzten sich automatisch aus den Dateinamen zusammen. Hab's etwas einheitlicher aber immer noch international gemacht. Zusätzlich gibt's einen Pfeil am Menüpunkt, damit sollte es eindeutiger sein das man hier ein Dropdown aufmachen kann.

**Comment by BITS-Editor** [comment]
Kann man dann wenigsten "BITS" in Großbuchstaben schreiben?

**Comment by andi-blafasl** [comment]
Leider nein.

**Comment by BITS-Editor** [comment]
Kann ich das woanders als Issue platzieren?

**Comment by andi-blafasl** [comment]
na klar ->  https://github.com/McShelby/hugo-theme-relearn
McShelby müsste die komplette Theme-Varianten logik überarbeiten.

**Comment by BITS-Editor** [comment]
Erledigt, siehe https://github.com/McShelby/hugo-theme-relearn/issues/332

**Comment by BITS-Editor** [comment]
Hier geschlossen und weiter später bei #129
