### ISSUE TITLE
Zeichensatz der HTML-Dateien

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#130]
Mit den neueren MS SharePoint-Versionen können keine HTML-Seiten mehr als Ordner importiert und als Webseiten angezeigt werden.

Ein Workaround ist offenbar die Umbenennung von .html- in .aspx-Dateinamen. Hierbei werden jedoch die BITS-Seiten nicht mit Umlauten dargestellt. 

Der Grund scheint der falsche Zeichensatz bei der Erzeugung der HTML-Seiten aus den Markdown-Seiten zu sein, siehe https://social.msdn.microsoft.com/Forums/de-DE/43641b0b-f201-4512-ab41-a69fb56d05c5/umlaute-werden-in-webseite-falsch-aber-in-visual-studio-korrekt-dargestellt?forum=aspnetajaxmvcde 

Können wir den Zeichensatz beim Exportieren auf Unicode (UTF8 mit Signatur) - Codepage 65001 stellen?

**Comment by andi-blafasl** [comment]
Ich hab mich in das Thema kurz eingelesen. Die erzeugten HTML-Dateien sind UTF-8 ohne Signatur. Codepage 65001 ist in Windows eine legacy kompatible Bezeichnung für UTF-8. 
Die Signatur (oder BOM genannt) sollte nicht in HTML-Dateien enthalten sein: https://www.w3.org/International/questions/qa-utf8-bom.de.html

Auch Hugo hat (oder hatte) Probleme wenn in den Quellen BOM verwendet wird:

- https://github.com/gohugoio/hugo/issues/4895
- https://discourse.gohugo.io/t/character-encoding-in-content-files/1316

Innerhalb der HTML-Seiten ist alles korrekt gesetzt und sowohl direkt aus dem Dateisystem als auch über einen Webserver werden Umlaute richtig dargestellt. Ich gehe davon aus das SharePoint durch das umbenennen in ASPX serverseitig die Dateien interpretiert und die neu erzeugte Ausgabe dann nicht korrekt mit UTF-8 formatiert ist. Da es durch das einfügen des BOM zu unvorhersehbaren Probleme kommen könnte, würde ich das nicht generell machen. Wer diese spezielle Anforderung hat, muss beim umbenennen dann halt auch das BOM einfügen. Zudem hab ich bei Hugo nichts gefunden wie man die Ausgabe auf UTF-8 mit BOM umstellen kann.

**Comment by BITS-Editor** [comment]
Danke! Verstehe. Offenbar ist der SharePoint hier auf eine Legacy-Erweiterung angewiesen. Die sollten wir dann nicht in BITS-hugo einbauen.
