### ISSUE TITLE
Tab-Tasten-Navigation im Quiz kaputt

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#132]
Leider geht in Chrome-basierten Browsern die Tab-Tasten-Navigation auf jeder ersten Seite der Quizzes nicht.

Ich habe ein Issue hier erstellt: https://github.com/bonartm/quizdown-js/issues/32

**Comment by andi-blafasl** [comment]
Ok, in Chrome geht's manchmal. Ich konnte das Problem nachvollziehen, aber hab keine Ahnung wo genau das hängt.

**Comment by BITS-Editor** [comment]
UPDATE:
Der Bug ist nur in chrome-basierten Browsern vorhanden.

**Comment by BITS-Editor** [comment]
Der Workaround ist in der Seite https://github.com/BITS-Training/BITS-hugo/blob/main/content/Barrierefreiheit.de.md#chrome-basierte-browser-chrome-ms-edge-vivaldi-etc erläutert.

**Comment by andi-blafasl** [comment]
Das Problem schein nicht mehr zu bestehen. Ich kann in Chrome das Quiz mit der Tastatur bedienen. Getestet hab ich das auch komplett ohne Maus. Also von der vorherigen Seite mit Tastatur zum Quiz navigiert und dann mit Tab und Pfeiltasten einmal komplett ein Quiz durchgearbeitet. Keine Probleme.

Bitte noch mal jemand anderes testen.

**Comment by BITS-Editor** [comment]
Ja, das Problem besteht nicht mehr, getestet mit Chrome, Edge und Vivaldi, aktuelle Version 02.12.2023. Ich passe den Hilfetext an.
