### ISSUE TITLE
Bootstrap Framework noch in Verwendung in v6?

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#14]
Nutzen wir noch das Bootstrap-Framework? Wenn ja, welche Version? Wir müssten dann die Starseite und die Seite Herausgeber und Lizenz anpassen.

**Comment by andi-blafasl** [comment]
so weit ich das sehe, nein. Ich würde für die Infos bezüglich Herausgeber und Lizenz auf das Learn Theme verweisen. Da kann sich ja auch in Zukunft was ändern und wir nutzen das ja fast unverändert.

**Comment by BITS-Editor** [comment]
Bootstrap ist nicht mehr integriert, alle Hinweise im Text sind gelöscht.
