### ISSUE TITLE
Relearn Theme Update > 5.3.x

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#145]
Im Branch [theme-update](https://github.com/BITS-Training/BITS-hugo/tree/theme-update) sammeln wir alle Anpassungen die für das Theme Update auf die aktuellste Version (derzeit 5.23.2) nötig sind.
Unter [bits-training.github.io](https://bits-training.github.io/) steht die DEV-Version mit neuem Theme zum testen bereit und wird nach Änderungen aktuell gehalten.

Die Commits sind granular für die jeweilige Änderung und in der Beschreibung wird die URL zum Change-Log des Themes eingefügt. So kann man die einzelnen Anpassungen einfach nachvollziehen und bei Problemen schnell zur Dokumentation springen.

Hier sammeln wir alle Probleme die nach dem Update auffallen und noch gelöst werden müssen.

**Comment by andi-blafasl** [comment]
Die Suche baut keinen Index mehr auf

**Comment by andi-blafasl** [comment]
Suche geht wieder: https://github.com/McShelby/hugo-theme-relearn/issues/743#issuecomment-1836844270

**Comment by andi-blafasl** [comment]
Theme 5.24 -> https://github.com/McShelby/hugo-theme-relearn/issues/744

**Comment by McShelby** [comment]
Ich habe ein Beispiel an mein Kommentar gehängt, um das Problem mit dem Titel auf der Startseite zu lösen. Geht dann ab 5.24.0, dass hoffentlich bald kommt.

https://github.com/McShelby/hugo-theme-relearn/issues/743#issuecomment-1836915475

**Comment by andi-blafasl** [comment]
Theme aktualisiert auf 5.27.0. Die Änderungen an 6.x sind aktuelle nicht relevant und zu viele "breaking changes"
