### ISSUE TITLE
HowTo: GitHub Pages erstellen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#148]
Ablauf:

1. Die beiden Repos [bits-training.github.io](https://github.com/BITS-Training/bits-training.github.io.git/) und [BITS-Hugo](https://github.com/BITS-Training/BITS-hugo.git) sind in einem gemeinsamen Verzeichnis gecloned

- c:\...\documents\BITS-hugo
- c:\...\documents\BITS-Training.github.io

2. Im Repo BITS-Training.github.io den "Test"-Branch auschecken.

3. Im Repo BITS-hugo den zu überführenden Branch auschecken

4. hugo im BITS-hugo Verzeichnis wie folgt ausführen: 
hugo --destination ..\BITS-Training.github.io --cleanDestinationDir --environment dev

5. Im Repo BITS-Training.github.io die Änderungen übernehmen, commiten und pushen

- git add -A
- git commit -m "hier sinnvollen Kommentar einfügen"
- git push

6. Kurze Zeit später sollte https://bits-training.github.io/ die Änderungen anzeigen.

7. Durch die Option "--environment dev" beim hugo-Aufruf steht in jeder Datei die genaue Uhrzeit, wann sie erstellt wurde.

- siehe Quelltext --> HTML head -->  meta name="date" content="10 Apr 24 15:38 CEST"

Wichtig ist, dass man auf keinen Fall den "MAIN" Branch im Repo BITS-Training.github.io verändert. Das ist die Grundlage für [www.bits-training.de](http://www.bits-training.de/)

**Comment by andi-blafasl** [comment]
Das erstellen der github Pages ist jetzt über eine action automatisiert. Ein Push auf den _main_ oder _develop_ Branch triggert das Erstellen der page im Test-Branch des **BITS-Training.github.io** branches
