### ISSUE TITLE
Interne Links zu Lektionen sind kaputt

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#149]
Zumindest in der Fileserver-Version von https://github.com/BITS-Training/BITS-hugo/releases/tag/v6.5-rc1 werden die internen Links zu anderen Lektionen nicht richtig angezeigt, z.B. unter 06-lektion-social-media/03-social-media-sicher-nutzen.html oder 01-lektion-e-mails/03-spam-e-mails.html oder 09-lektion-mein-arbeitsplatz/02-passwoerter-nicht-weitergeben.html

![Unbenannt](https://github.com/BITS-Training/BITS-hugo/assets/7092938/87cf85a0-a16b-4716-9176-9e80163b7112)

Das gilt aber nicht für alle Links, siehe den funktionieren den unter 10-lektion-kuenstliche-intelligenz/03-gefahren-von-ki-ii.html

**Comment by andi-blafasl** [comment]
seit Version [5.23.0](https://mcshelby.github.io/hugo-theme-relearn/basics/migration/index.html#5230) des Relearn Theme, haben Links eine andere Syntax und müssen nicht mehr in relref shortcodes gepackt werden. Dafür muss das Linkziel jetzt so eingetragen werden, wie später die Seite genannt wird. Also nicht mehr so, wie sie im Dateisystem liegt!

Anpassungen an den Links sind gemacht.
Bitte testen.

**Comment by BITS-Editor** [comment]
Sieht gut aus.

Passt die Erläuterung unter 3. Interne Links https://github.com/BITS-Training/BITS-hugo/blob/release-6.5-fixes/ReLearnTheme-HowTo.md  noch?

**Comment by andi-blafasl** [comment]
Die hab ich auch angepasst. Müsste so passen.

**Comment by BITS-Editor** [comment]
Super, dann passt das ja.
