### ISSUE TITLE
Verbesserungsvorschlag Kapitel E-Mails – Computervieren per Mail

### ISSUE THREAD

**Issue by BerlinCERT** [BITS-Training/BITS-hugo#150]
(/01-lektion-e-mails/04-computerviren/index.html)
Bei der Durchsicht der Erklärungen, ist die Aussage „Allein das Betrachten einer E-Mail kann einen Virus aktivieren“ aufgefallen. Diese Aussage ist m. E. etwas zu allgemein und könnte zum besseren Verständnis etwas präzisiert werden, um besser zu verstehen, unter welchen Umständen dies möglich ist. Vielleicht folgendermaßen:
"Um einen schädlichen Programmcode allein durch das Betrachten einer E-Mail auszuführen, müssen bestimmte Voraussetzungen erfüllt sein. Moderne E-Mail-Clients und Betriebssysteme sind normalerweise gut gegen solche Angriffe geschützt, jedoch besteht immer ein gewisses Restrisiko:

- **Automatische Ausführung von Skripten:** Einige E-Mail-Programme können so eingestellt sein, dass sie Skripte oder Makros automatisch ausführen. Dies kann dazu führen, dass potenziell gefährlicher Code aktiviert wird, sobald die E-Mail geöffnet wird.
- **Anzeige von HTML-Inhalten:** E-Mails im HTML-Format können eingebettete Skripte oder andere schädliche Elemente enthalten. Falls der E-Mail-Client automatisch HTML-Inhalte rendert, könnte dies ein Risiko darstellen.
- **Vorschau-Funktion:** Manche E-Mail-Clients zeigen eine Vorschau der eingehenden Nachrichten. Diese Funktion kann ausreichend sein, um schädlichen Code auszuführen, besonders wenn sie so konfiguriert ist, dass sie HTML-Inhalte oder Anhänge automatisch lädt.
- **Sicherheitslücken in der Software:** Auch gut konfigurierte E-Mail-Clients können durch unentdeckte oder nicht behobene Sicherheitslücken verwundbar sein, die es einem Angreifer erlauben, schädlichen Code zu starten, sobald die E-Mail angezeigt wird.

Es ist daher wichtig, dass E-Mail-Clients sorgfältig konfiguriert sind und Benutzer, insbesondere beim Umgang mit Nachrichten von unbekannten Absendern vorsichtig sind. Das Bundesamt für Sicherheit in der Informationstechnik (BSI) bietet weiterführende Empfehlungen und Sicherheitstipps zum sicheren Umgang mit E-Mails. (https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Sicherheitsirrtuemer/irrtuemer-e-mail-sicherheit.html)"

**Comment by BITS-Editor** [comment]
Vielen Dank! Schaue ich mir an!

**Comment by BITS-Editor** [comment]
Ich habe die Vorschläge leicht angepasst übernommen. Wir dürfen bei den Nutzenden nicht den EIndruck erwecken, dass deren Behörde das E-Mail-Programm nicht sicher konfiguriert hat. Die neuen Inhalte habe ich mit der Expand-Funktion eingebettet; bei den Handlungsempfehlungen habe ich ergänzt: "keine Änderungen an den Sicherheitseinstellungen Ihres E-Mail-Programms vornehmen,"

Siehe Commit https://github.com/BITS-Training/BITS-hugo/commit/74924c083229c9a27ea1900e706a9492d1f87512

**Comment by BerlinCERT** [comment]
Vielen Dank für Ergänzungs- und Änderungsvorschläge, welche die Sachverhalte unseres Erachtens gut darstellen.

**Comment by BITS-Editor** [comment]
Das freut mich! Wir prüfen, wann wir eine neue Version veröffentlichen; das dürfte aber etwas dauern.
