### ISSUE TITLE
Verbesserungsvorschlag Kapitel Passwörter – Der richtige Umgang

### ISSUE THREAD

**Issue by BerlinCERT** [BITS-Training/BITS-hugo#151]
(/03-lektion-passwoerter/03-der-richtige-umgang/index.html)
Im Rahmen der Durchsicht der BITS-Lektion ist mir aufgefallen, dass der Begriff „Passwortkarten“ verwendet wird, ohne dass dieser zuvor eingeführt oder erklärt wurde. Um Verwirrung zu vermeiden, wäre eine Definition dieses Begriffs sinnvoll oder man sollte alternativ die Verwendung dieses Begriffs in der Dokumentation entfallen lassen.
Als Definition könnte folgendes verwendet werden: „Passwortkarten sind ein praktisches Werkzeug zur sicheren Authentifizierung. Sie bestehen häufig aus einer physischen Karte, die ein Gitter oder eine Matrix aus Zahlen und Buchstaben aufweist. Nutzer können nach einer bestimmten Regel, beispielsweise der Auswahl von Zeichen entlang einer vorgegebenen Reihe oder Spalte, daraus ein Passwort generieren. Hier einige Vorteile und Nutzungsmöglichkeiten von Passwortkarten:

- **Erzeugung von Passwörtern:** Eine Passwortkarte kann zur Erstellung von starken, schwer zu erratenden Passwörtern verwendet werden, indem aus der Matrix zufällige Zeichenfolgen ausgewählt werden.
- **Physisches Sicherheitsmerkmal:** Da es sich um ein physisches Objekt handelt, bietet die Passwortkarte einen zusätzlichen Sicherheitsfaktor – etwas, das der Benutzer besitzt. Ohne die Karte kann das Passwort nicht reproduziert werden.
- **Vielseitige Anwendung:** Passwortkarten können für mehrere Konten verwendet werden, indem für jedes Konto unterschiedliche Koordinaten oder Regeln zur Auswahl der Passwörter festgelegt werden.
- **Zusätzliche Sicherheit durch Benutzerdefinierte Regeln:** Die Sicherheit kann erhöht werden, indem persönliche oder nur dem Benutzer bekannte Regeln für die Auswahl der Passwörter auf der Karte verwendet werden.

Passwortkarten erweisen sich als besonders nützlich in Umgebungen mit hohen Sicherheitsanforderungen, wo Benutzer physische Hilfsmittel zur Authentifizierung nutzen können. Auch wenn sie nicht so verbreitet sind wie andere Passwortverwaltungsmethoden, wie digitale Passwortmanager, bieten sie doch eine wertvolle Alternative zur Erhöhung der Datensicherheit.“

**Comment by BITS-Editor** [comment]
Vielen Dank! Schaue ich mir an!

**Comment by BITS-Editor** [comment]
Der Begriff "Passwortkarte" wird hier erklärt:
https://www.bits-training.de/training/03-lektion-passwoerter/04-werkzeuge-fuer-passwoerter/

Ich habe eine Ergänzung auf Grundlage dieses Issues vorgenommen, siehe
Commit https://github.com/BITS-Training/BITS-hugo/commit/5c93c9a2ca6fe2e5ac2fc19c55b335a4c51407ef

Passt das so? Ich wollte den Absatz nicht zu lang werden lassen.

**Comment by BerlinCERT** [comment]
Vielen Dank für Ergänzungs- und Änderungsvorschläge, welche die Sachverhalte unseres Erachtens gut darstellen.

**Comment by BITS-Editor** [comment]
Das freut mich! Wir prüfen, wann wir eine neue Version veröffentlichen; das dürfte aber etwas dauern.

**Comment by BITS-Editor** [comment]
Wird umgesetzt.
