### ISSUE TITLE
Verbesserungsvorschlag Kapitel Mobile Geräte – Quiz

### ISSUE THREAD

**Issue by BerlinCERT** [BITS-Training/BITS-hugo#152]
(08-lektion-mobile-geraete/90-quiz-mobile-geraete/index.html)
Es ist aufgefallen, dass bei dem Quiz zu der Frage „Jemand möchte Ihnen dienstliche Daten auf einem USB-Stick übergeben. Wie verhalten Sie sich?“ die Antwortmöglichkeiten mehrere Interpretationen zulässt, doch eine klare Erklärung unter dem Punkt „‚Mobiler Datenträger“ fehlt.
Um ein besseres Verständnis zu ermöglichen, habe ich die verschiedenen Optionen genauer betrachtet:

- **Ich stecke den Stick in meinen Computer und bearbeite die Daten.**
Diese Option könnte riskant sein, da der USB-Stick schädliche Software enthalten könnte.
- **Ich bitte die Person, mir die Daten elektronisch per E-Mail zuzusenden oder mir einen Download-Link zu schicken.**
Diese Methode reduziert das Risiko einer Malware-Infektion, da keine physischen Medien verwendet werden, die kompromittiert sein könnten.
- **Ich schaue mir den Stick zunächst auf einem Computer ohne Netzwerkanbindung an, um festzustellen, dass die gewünschten Dateien auch enthalten sind. Erst dann kann der USB-Stick im Zielsystem verwendet werden.**
Dies ist eine sichere Herangehensweise, bei der zuerst überprüft wird, ob der Stick sichere Inhalte hat, ohne das Risiko, Netzwerksysteme zu infizieren.
- **Ich kopiere die Daten vom USB-Stick auf meinen privaten Laptop und sende sie dann an mein dienstliches E-Mail-Postfach.**
Diese Option könnte auch unsicher sein, da der private Laptop kompromittiert werden könnte, was Risiken für dienstliche Systeme darstellt.

Eine Überarbeitung der Fragestellung und der Antwortmöglichkeiten, sowie eine detailliertere Erklärung könnten hilfreich sein, um mehr Klarheit zu schaffen und die Benutzer besser zu schulen.

**Comment by BITS-Editor** [comment]
Vielen Dank! Schaue ich mir an!

**Comment by BITS-Editor** [comment]
Ich finde den Hinweis wichtig und richtig. Allerdings ist der Antwortvorschlag mit dem Offline-Rechner mE realitätsfern, zumindest für die meisten Beschäftigten in Behörden. Ich würde daher diese Option bei den Antwortmöglichkeiten streichen.

Wäre das ok?

**Comment by BerlinCERT** [comment]
Vielen Dank für Ergänzungs- und Änderungsvorschläge, welche die Sachverhalte unseres Erachtens gut darstellen. Wird daraus die Version 6.5.1 kurzfristig veröffentlicht?

**Comment by BITS-Editor** [comment]
Das freut mich! Wir prüfen, wann wir eine neue Version veröffentlichen; das dürfte aber etwas dauern.
