### ISSUE TITLE
Startseite der einzelnen Lektionen - Layout

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#16]
Der Text "In dieser Lektion lernen Sie," sollte linksbündig mit den Aufzählungspunkten sein.

**Comment by andi-blafasl** [comment]
Das kann über die theme-bits.css angepasst werden.

**Comment by BITS-Editor** [comment]
Bei mir lokal ist der Text "In dieser Lektion lernen" sie weiterhin zentriert. Wo muss ich das in der theme-bits.css anpassen?

**Comment by andi-blafasl** [comment]
@BITS-Editor du musst das garnicht anpassen. das kommt wenn ich es pushe automatisch in den main branch. du musst das dann nur in deinen branch mergen ;-)

**Comment by BITS-Editor** [comment]
> @BITS-Editor du musst das garnicht anpassen. das kommt wenn ich es pushe automatisch in den main branch. du musst das dann nur in deinen branch mergen ;-)

Wie merke ich, dass ich mergen kann?
