### ISSUE TITLE
hugo Warnung zu veralteten Funktionen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#165]
Bei Verwendung von hugo 0.133.0 kommt beim Aufruf von hugo server Folgendes:

WARN  deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in a future release. Use .Sites.Default instead.
WARN  deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in a future release. Use .Site.Params instead.
WARN  deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in a future release. Use hugo.IsMultilingual instead.

Kannst Du das fixen, @andi-blafasl ?

**Comment by andi-blafasl** [comment]
Das sind alles Punkte die aus dem Theme kommen. Und da es nur eine deprecated Warnung ist und wir für die Erzeugung die 133.1 empfehlen, lassen wir das so. Ich mache keinen Theme update ein einer Point-1 Version.

**Comment by LasseKrache** [comment]
Hallo,

Ich bin erst kürzlich über dieses Projekt gestolpert und versuche es an meine Bedürfnisse anzupassen. Jetzt habe ich gesehen, dass die oben genannten WARN-Meldungen mittlerweile ERROR sind und das Projekt so wohl nicht mehr läuft. Ich weiß, dass es nur am Theme liegt, aber da ich mich mit Hugo nicht gut (genauer: gar nicht!) auskenne, weiß ich nicht, wie ich da weiterkomme ...
Ist geplant, die wohl erforderlichen Anpassungen vorzunehmen?

> ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Implement taxonomy 'social' or use .Site.Params.Social instead.
> ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.137.0. Use hugo.IsMultilingual instead.

Danke für das Projekt ... und ggf. für ein kurzes Feedback!

**Comment by andi-blafasl** [comment]
Hi, wir verwenden bisher die 0.133.1 die den release. Siehe meine letzte Nachricht oben. Am besten lokal auch einfach diese Hugo version nutzen.

**Comment by LasseKrache** [comment]
Okay, werde ich versuchen.
Danke für das Feedback! :-)
