### ISSUE TITLE
Barrierearmut - Tastaturnavigation bei class="expand"

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#168]
Die Inhalte von class="expand" lassen sich per Tastaturnavigation über die Tab-Taste und die Leertaste anzeigen. Anschließend funktioniert die Seitennavigation vor/zurück per Tastatur nicht mehr.

Könnte man den Pfeil-Buttons rechts oben eine Tastenkombination zur Auswahl bzw. zum Auslösen zuordnen?

**Comment by andi-blafasl** [comment]
Wenn man mit Tab von den Expands wegspringt, dann funktioniert die Tastaturnavigation über die Pfeiltasten wieder.

**Comment by BITS-Editor** [comment]
Stimmt. Danke!
