### ISSUE TITLE
Barrierearmut - Tastaturnavigation zu Links

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#169]
Links in BITS können nicht per Tastatur angesteuert und aufgerufen werden.

**Comment by andi-blafasl** [comment]
Mit Tab kommt man irgendwann an den Link (je nach dem wie viele links in der Seitenleiste sind) und kann ihn dann mit Enter aufrufen.

**Comment by BITS-Editor** [comment]
Stimmt. Danke!

**Comment by BITS-Editor** [comment]
Offenbar ein Bug in Vivaldi - in Firefox und Edge funktioniert klappt das in der Tat , in Vivaldi nicht.
