### ISSUE TITLE
Interne Links ersetzen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#18]
Wie setze ich interne Links in BITS?

z.B. http://localhost:1313/030-lektion-e-mail/03.spam-e-mails/ auf die Virus-Lektion
http://localhost:1313/030-lektion-e-mail/04.computerviren/ auf Virus-Lektion und Ansprechpersonen
http://localhost:1313/030-lektion-e-mail/05.phishing-und-pharming/ auf Lektion Internet
http://localhost:1313/030-lektion-e-mail/08.umgang-vertraulichen-informationen/ auf Ansprechpersonen
http://localhost:1313/030-lektion-e-mail/16.zusammenfassung/ auf Ansprechperson

**Comment by andi-blafasl** [comment]
Nimm den Shortcode von Hugo: https://gohugo.io/content-management/cross-references/

**Comment by BITS-Editor** [comment]
Ja, aber welchen Pfad? Das hier klappt nicht:
Mehr dazu sogleich und in der Lektion [Viren]({{< ref "/040-lektion-viren"  >}}).

**Comment by andi-blafasl** [comment]
Als Pfad nimmst einfach den aus dem Dateisystem: 

```
Mehr dazu sogleich und in der Lektion [Viren]({{< ref "/040 lektion viren" >}}).
```

**Comment by BITS-Editor** [comment]
Ersetzen der Ansprechperson:
(https://bits-training.de/bits/allgemeines/ansprechpartner/index.htm)
durch
({{< ref "/200 infos und ansprechpersonen/01.Ansprechpersonen.de.md" >}})

Die internen Links in den Lektionen 1-3 habe ich ersetzt.

In den anderen Lektionen ist dies nach Übernahme in die .md-Dateien nachzuholen.

**Comment by BITS-Editor** [comment]
Links zur Seite der Ansprechpersonen global ersetzen auf die Unterseite.

**Comment by BITS-Editor** [comment]
Ich habe jetzt alle Links zur "Ansprechperson" aktualisiert.

**Comment by BITS-Editor** [comment]
Sollten wir nicht den Link zur Seite ({{< ref "/200 infos und ansprechpersonen/01.Ansprechpersonen.de.md" >}}) als Parameter hinterlegen?

**Comment by andi-blafasl** [comment]
Warum sollte der Link als Parameter gesetzt werden? Ich sehe da gerade keinen Sinn für. Das besprechen wir beim nächsten Meeting.

**Comment by BITS-Editor** [comment]
Mmmh, als ich das schrieb, dachte ich, dass man eine individuelle Seite dann nehmen kann, z.B. auch eines außerhalb BITS. Aber jetzt denke ich: "So ein Quatsch". Also: vergiss es :-)
