### ISSUE TITLE
Änderung note in hugo-learn-theme

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#19]
Ich habe in der Datei
\themes\hugo-theme-learn\i18n\de.toml
den Text der [note "other"] von "Anmerkung" auf "Achtung" geändert.
Müssen wir was bei Änderungen des main-Branches beim Learn-Theme und mergen beachten?

**Comment by andi-blafasl** [comment]
Die Änderung muss im Theme Repo gepusht werden und dann der neue Commit im BITS Repo aktulisiert werden.

**Comment by BITS-Editor** [comment]
> Die Änderung muss im Theme Repo gepusht werden und dann der neue Commit im BITS Repo aktulisiert werden.

Soll ich das jetzt schon machen oder lieber warten?

**Comment by andi-blafasl** [comment]
so, wieder einmal finde ich Hugo genial 😍

Es ist ganz einfach einzelne Teile der i18n Übersetzung im Theme durch lokale Anpassungen zu überschreiben. Man erstellt einfach im eigenen Ordern einen i18n Ordner und fügt dort Dateien des Themes mit gleichem Namen ein. Der Inhalt hat dann beim Erstellen der Seite Priorität, aber alles was nicht in der Datei steht wird trotzdem aus der im Theme enthaltenen Datei geholt. Ich habe das in einem Test-Branch umgesetzt: [translation-test](https://github.com/BITS-Training/BITS-hugo/tree/translation-test) 
In diesem Branch hab ich auch die Variablen die wir für den Text "Behörde oder Einrichtung" verwenden wollen angepasst. Die sind jetzt auch einfach übersetzbar in der config.toml eingebaut. Wenn du den Test-Branch bei dir einbaust musst du die Variablen in deinem Content einmal per Suchen&Ersetzten austauschen. In meinem [Commit ](https://github.com/BITS-Training/BITS-hugo/commit/dc985d5ed94b5fd9e5769ed40b55b8d64e17cb13) siehst du die Änderung schön dargestellt.

**Comment by BITS-Editor** [comment]
Erledigt, klasse!
