### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#25]
Was wollen wir unter dem Punkt "Mehr" anbringen?

z.B. Datenschutz, Ansprechpartner usw...

**Comment by BITS-Editor** [comment]
Ist fast fertig.
Offen sind die Inhalte für 

- Download - Hinweise auf git/hugo
- Download - Link zum ZIP-Archiv
- Barrierefreiheit - Tastaturnavigation? Kontraste?

Bitte entfernen:

- Mehr
- und alle Unterpunkte 
- 

- von Mehr

-

**Comment by andi-blafasl** [comment]
Ich dachte die Punkte "Download" usw kommen unterhalb von "Mehr"?

**Comment by BITS-Editor** [comment]
Gerne. Wie bekommen wir denn die Download-Seite nach unterhalb von "Mehr"?

**Comment by BITS-Editor** [comment]
1. oben bleibt nur "Ansprechpersonen"
2. Der Rest ersetzt alles unter "Mehr"
3. Download wir ganz gelöscht.

**Comment by andi-blafasl** [comment]
Alles angepasst.
