### ISSUE TITLE
BITS-Version anzeigen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#3]
Auf jeder Seite sollte, vielleicht rechts oben, die BITS-Version stehen.

**Comment by BITS-Editor** [comment]
Ich hätte es vielleicht eher links unter unser Logo gepackt, also zwischen Logo und Suchschlitz.
Sorry, hätte ich vielleicht vorher sagen sollen.

**Comment by andi-blafasl** [comment]
Kein Problem, deshalb hab ich es ja auch erstmal ziemlich quick und dirty eingebaut. Jetzt ist die Version links in der Sidebar. So ganz trennen kann ich mich von der "Badge" variante aber noch nicht. Wie gefällt es dir jetzt?

**Comment by BITS-Editor** [comment]
Gut, aber die Schrift ist zu hell :-)

**Comment by BITS-Editor** [comment]
In meiner Version ist jetzt wieder das quer laufende Banner da. Mist.

**Comment by andi-blafasl** [comment]
was meinst du mit quer laufendem Banner? Ich hatte das beim letzten Update so gemacht:
![image](https://user-images.githubusercontent.com/3586675/121082431-5fde3f80-c7de-11eb-8d06-974e64149318.png)

Sah das bei dir zwischenzeitlich mal anders aus???

**Comment by BITS-Editor** [comment]
Ich könnte schwören, dass ich einmal eine Darstellung hatte, bei der das Band horizontal zwischen dem BITS-Logo und dem Suchschlitz war. Das fand ich sehr schick. Ginge das? Mit dem quer laufenden Banner sieht das so aus, als ob das eine befristete Aktion oder so was sei.

**Comment by BITS-Editor** [comment]
Lutz prüft nochmal, ob wir das so lassen.

**Comment by BITS-Editor** [comment]
Die Gattin meint, dass der Versionshinweis unterhalb des Logos stehen sollte. Ich frage morgen nochmal andere Leute.

**Comment by andi-blafasl** [comment]
Ich hab's mit meiner Cousine gezeigt. Ihre Meinung: Warum muss überhaupt auf jeder Seite und immer die Version stehen? Ich denke auch die Version auf der Startseite reicht. Welchen Mehrwert hat der Endanwender wenn da immer die Version links im Menü steht?

**Comment by BITS-Editor** [comment]
Wir können das jetzt so lassen. Für mich war das hier in HH immer gut um zu sehen, welche Version die Stadt nutzt - die ist immer hinten dran. Das finde ich aber auch so raus. Danke!
