### ISSUE TITLE
Linkfarbe

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#32]
Die Farbe für Links ist zu blass.

**Comment by andi-blafasl** [comment]
Das WAVE Tool sieht hier keine probleme: https://wave.webaim.org/report#/https://bits-training.github.io/200-infos-und-ansprechpersonen/03.herausgeber-und-lizenz/

**Comment by BITS-Editor** [comment]
Aber meine Augen ;-)

Wir können das aber auch so lassen - vielleicht war gestern mein Bildschirm schlecht ausgeleuchtet. Wenn Du den Kontrast ganz subjektiv ok findest, können wir hier auch das Issue schließen.

**Comment by andi-blafasl** [comment]
Das können wir auch in einer Beta-Phase nochmal prüften. Wenn man die Links dunkler macht find ich wirkt das nicht mehr so schön modern. Vielleicht machen wir für bessere Lesbarkeit noch eine Version mit extremen Kontrasten? Sowas gibt's ja auch bei manchen Seiten oder Apps oder auch bei Android/iOS.
Ich mach den hier zu und wir sehen dann ob beim Beta-Test die Anforderung nochmal aufkommt.
