### ISSUE TITLE
Tastaturnavigation

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#37]
Unterstützt BITS v6 die Navigation per Tastatur?
https://bits-training.de/bits/allgemeines/dokumente/index.htm

**Comment by BITS-Editor** [comment]
Immerhin.

In v5 sind die Kapitel mit Metadaten versehen, die man per Tastaturkürzel dann ansteuern kann. Das müsste doch auch mit v6 möglich sind.

**Comment by andi-blafasl** [comment]
ich hab mir das in der v5 schon angeschaut. Aber ohne die Erklärung der Tastaturkürzel weiß man das nicht. Ich frag mich, was das dann bringt. Naviegiren kann man die neue Seite ja sehr gut ohne Maus  und nur mit der Tastatur. Das geht mit TAB und Pfeiltasten für mich ganz intuitiv ohne das ich irgendwelche AccessKeys auswendig lernen muss. Probier das doch mal aus.

**Comment by BITS-Editor** [comment]
Das Navigieren mit Pfeilen funktioniert, das hatte ich getestet.
Numerierung etc. ist nicht selbsterklärend, das stimmt. Aber über das Konzept des AccessKey-Pad (siehe ext. Link oben) wüssten die betroffenen Personen, dass das eine Zugang wäre. Wir müssten dann die Seite, auf der die Zuordnung erklärt wird, z.B. mit der 9 belegen.

Ich weiß halt nicht, wie wichtig das ist - und ob nicht ein wenig Aufwand bei uns die Zugänglichkeit erheblich verbessert.

**Comment by BITS-Editor** [comment]
Jetzt fällt mir ein, dass ein individuelles Ergänzen mit HTML vielleicht gar nicht so einfach ist?!?

**Comment by andi-blafasl** [comment]
Also da das Menü dynamisch generiert wird, sehe ich da aktuell keine Möglichkeit das einzubauen. Um das dynamisch oder konfigurierbar hinzubekommen wäre eine sehr große Anpassung des Themes nötig.
Können wir das mit Betatestern oder einer Umfrage bei Usern die du kennst abfragen ob das jemand benötigt? Wenn es keiner braucht wäre das schon schade um die Zeit.

**Comment by BITS-Editor** [comment]
Verstehe ich. Wir lassen es dann erstmal so. Ich verweise dann in der Info-Seite zur Barrierefreiheit nur auf die Tastaturnavigation mit den Pfeiltasten.

Der Bedarf als solcher ist sicher nicht groß, aber im öffentlichen Dienst ist Barrierefreiheit ein wichtiges Thema. Wir sollten daher das Issue noch offen lassen.

**Comment by BITS-Editor** [comment]
Wir machen in #77 weiter.
