### ISSUE TITLE
ZIP-Datei für Release erstellen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#38]
Lutz passt die Readme.txt an

Die ZIP-Datei erstellen wir am Ende.

**Comment by BITS-Editor** [comment]
Readme.txt ist angepasst, Andreas müsste noch einmal auf die offenen technischen Punkte schauen (markiert mit XXX).

**Comment by andi-blafasl** [comment]
Readme im Hauptverzeichnis angepasst. Readme im Static-Ordner und LearnTheme-howto als Markdown konvertiert und angepasst.

**Comment by BITS-Editor** [comment]
Die Readme im Static-Ordner enthält noch einen Platzhalter zur Frage, welche Datei für die Nutzung von den Beschäftigten aufgerufen werden muss.

**Comment by andi-blafasl** [comment]
ich hab die Readme angepasst.

**Comment by BITS-Editor** [comment]
Und welche Datei muss bei der HTML-Version aufgerufen werden?

**Comment by andi-blafasl** [comment]
Steht in der README.md (static-Ordner) unter Punkt 4

"010-start.html"

**Comment by BITS-Editor** [comment]
> Steht in der README.md (static-Ordner) unter Punkt 4
> 
> "010-start.html"

Sehr gut! Jetzt müssen wir mE nur noch die Release-Datei basteln. Besprechen wir am 29.06. :-)

**Comment by BITS-Editor** [comment]
Betaphase läuft bis 15.7., dann ggf. Bugs fixen und Release der finalen Version.
