### ISSUE TITLE
Github-Homepage für BITS v6?

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#41]
Was soll zukünftig die Github-Homepage für BITS sein?
https://github.com/BITS-Training/BITS-hugo
oder wie bisher
https://github.com/BITS-Editor/BITS

**Comment by andi-blafasl** [comment]
ich würde Vorschlagen: https://github.com/BITS-Training/BITS-hugo

**Comment by BITS-Editor** [comment]
Ok.
