### ISSUE TITLE
Restanten in statischen Seiten / public-Ordner

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#42]
Eben habe ich über den einfache hugo-Befehl bei mir die statischen Seiten neu erzeugt. Dabei ist mir aufgefallen, dass ein alter Ordner unter public\200-infos-und-ansprechpersonen, der nicht mehr genutzt wird, anschließend noch vorhanden war.

1. Wie können wir sicherstellen, dass nicht solche Restanten verbleiben?

2. Ich sehe gerade, dass das public-Ordner ja gar nicht auf github liegt. Warum nicht?

3. Brauchen wir die Verlinkung zu public\images\gopher-404.jpg und die Datei selbst in 
\public\404.html, \public\en\404.html und in \themes\hugo-theme-learn\layouts\404.html ?

**Comment by andi-blafasl** [comment]
1. durch verwenden des Paramenters `--cleanDestinationDir` beim Erstellen oder durch löschen des Inhalts des `public`-Folders. Siehe auch [Basic Usage | Hugo](https://gohugo.io/getting-started/usage/)
2. Weil es keinen Sinn macht die generierten Seiten in das Quellcode-Repository zu packen. Der Ordern ist über die git-config ausgeschlossen.
3. die 404 Seite wird von hugo generiert (weil im Theme so vorgesehen) und kann in einer Web-Server-Konfig als Seite für nicht gefundenen Inhalt (Fehler 404) genutzt werden. Wir sollten die Design-Technisch noch ein bisschen anpassen.
