### ISSUE TITLE
404 Seite anpassen

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#45]
Die Fehler 404 Seite muss noch angepasst werden.

**Comment by andi-blafasl** [comment]
Bild und Layout angepasst.

**Comment by BITS-Editor** [comment]
Ich bräuchte noch die Lizenz-Info für die Readme im Static-Ordner und die Lizenz-Seite.

**Comment by andi-blafasl** [comment]
Ich hab das in der "\300 infos\Herausgeber-und-Lizenz.de.md" eingetragen.

**Comment by BITS-Editor** [comment]
https://unsplash.com/license
