### ISSUE TITLE
Home-Seite anpassen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#46]
1. Download-Link über Note  auf Release-Seite des Repositories (Lutz).
2.. Icon zur Start-, nicht zur Home-Seite (Andi).

**Comment by andi-blafasl** [comment]
Der "Home" link mit dem Icon geht jetzt auf die Seite "Start". Deshalb ist die jetzt im Menü nicht mehr als erster Punkt drin. Mit einem Klick auf das Logo kommt man auf die "Home" Page. Ich denke so ist das ganz gut nutzbar.

**Comment by andi-blafasl** [comment]
Eine Download-Link gibt's auf der Home-Page ja auch schon im Text. Ich glaub dann brauche wir gar keinen bunten Kasten dazu bauen.

**Comment by BITS-Editor** [comment]
Ich fände es gut, wenn auch das Logo zur Startseite ginge.

**Comment by andi-blafasl** [comment]
auf die schnelle ging das jetzt nicht. ich schau es mir am WE an.

**Comment by andi-blafasl** [comment]
Das Logo verlinkt jetzt auf allen Seiten (mit Ausnahme der Homepage) auf die 010-start Seite.

Die Ausnahme ist technisch bedingt weil so der Link von hugo generiert werden kann und nicht hardcoded in der partials/logo.html gesetzt werden muss. Damit ist der link immer richtig egal ober uglyURL=TRUE oder FALSE.
