### ISSUE TITLE
Quiz: Zurück-Funktion ab Frage 2?

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#47]
Ginge so etwas?

**Comment by andi-blafasl** [comment]
geht bestimmt, mach doch einen Vorschlag beim quizdown-Entwickler ;-)

**Comment by BITS-Editor** [comment]
Habe ich am 25.06.21 gemacht:
https://github.com/bonartm/hugo-quiz/issues/6#issue-930168186

**Comment by andi-blafasl** [comment]
Vielleicht machst du das Issue besser bei der eigentlichen [Quizdown Library](https://github.com/bonartm/quizdown-js) auf und nicht bei der Hugo Integration

**Comment by BITS-Editor** [comment]
Hihi!
https://github.com/bonartm/quizdown-js/issues/11#issue-932002890

**Comment by andi-blafasl** [comment]
https://bonartm.github.io/quizdown-js/
Version 0.4.1 ist aktuell und da gibt's jetzt einen Zurück-Button.
Sollen wir das noch in die finale Release einbauen oder machen wir das dann in version 6.0.1?

**Comment by BITS-Editor** [comment]
Gerne in die 6er!

**Comment by andi-blafasl** [comment]
Ist drin und du kannst es auf [bits-training.de](https://www.bits-training.de) testen

**Comment by andi-blafasl** [comment]
![image](https://user-images.githubusercontent.com/3586675/125828880-01de1e4c-640e-4a85-9518-2adcc213aafb.png)
Den Text mit der Erklärung musst du dann noch bei allen Quizzen anpassen. Ich hab da grad keine Idee wie man das jetzt sinnvoll formuliert 🤷‍♂️ Du hast da bestimmt eine gute Idee :wink:

**Comment by BITS-Editor** [comment]
Mache ich morgen, danke!

**Comment by BITS-Editor** [comment]
Ich habe gerade einen Pull gemacht, aber die Änderungen zeigen sich bei mir nicht in meiner lokalen Repository-Kopie. Kannst Du das bitte mal prüfen?

**Comment by andi-blafasl** [comment]
Jetzt ist Änderung drin. Hatte den push vergessen 🤦 Sorry

**Comment by BITS-Editor** [comment]
Jetzt hat es geklappt.
"**Bitte klicken Sie auf eine der Antwortmöglichkeiten. Mit den Pfeilen unterhalb der Fragen können Sie vor- und zurückgehen, am Ende klicken Sie auf den Doppelhaken, um zur Auswertung zu kommen. Die Glühbirne gibt Ihnen einen Tipp, mit dem kreisförmigen Pfeil starten Sie das Quiz neu.**

Ist leider recht lang, aber hoffentlich einfach und verständlich.

**Comment by andi-blafasl** [comment]
Hab mir das Thema Anleitung zum Quiz nochmal durch den Kopf gehen lassen. Was hälst du von einem Expand?
Siehe https://www.bits-training.de/030-lektion-e-mail/90.quiz-e-mails/
So kann man das sehr ausführlich erklären, stört aber nicht alle Leute die es Intuitiv verstehen und bedienen.
Die Änderung ist im Branch *Quiz-Anleitung* komplett umgesetzt

**Comment by BITS-Editor** [comment]
Sieht auf dem Handy gut aus, schaue ich mir Sonntag näher an.

**Comment by BITS-Editor** [comment]
Ich habe die Anleitung selbst minimal geändert, und dann nach oben oberhalb der Fragen verschoben. Ansonsten übersieht man sie vielleicht. Ich finde das gut so, Du auch?
