### ISSUE TITLE
Mouse-Over mit Link in Überschrift

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#5]
Auf zumindest einer Seite erscheint das Link-Symbol bei Mouse Over nach der Überschrift:
https://bits-training.github.io/020-einleitung/
Das sollte weg.

**Comment by andi-blafasl** [comment]
Das Link-Symbol erscheint bei allen überschriften. Es ist dafür gedacht, einen Link zu genau diesem Abschnitt zu teilen. Das macht schon sinn wenn man seine Benutzer auf bestimmte abschnitte hinweisen will.

**Comment by BITS-Editor** [comment]
Hmm, ich finde es eher verwirrend. Ist das dann auch nicht eher ein Anchor als ein Link?

**Comment by andi-blafasl** [comment]
Wenn du auf das Ketten-Icon klickst, dann kopiert er einen Anchor-Link:
http://localhost:1313/040-lektion-viren/02.was-ist-ein-computervirus/#was-ist-ein-computervirus

Ich hätte da bei uns in der Firma sogar schon eine Verwendung für: Den link kann man in eine Mail oder einen Aushang im Intranet packen und die Leute gezielt nochmal auf ein Thema verweisen.

**Comment by BITS-Editor** [comment]
Man könnte ja auch einfach auf die Seite verlinken ;-) Lass' uns da mal gemeinsam drüber reden bzw. Werners Meinung abwarten.

**Comment by andi-blafasl** [comment]
Ich close das hier mal. Wenn es später jemanden bei der Benutzer stört, dann kann man nochmal drüber nachdenken.
