### ISSUE TITLE
Quiz: Anleitung

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#51]
Wir sollten den Anleitungstext bei jeden Quiz ändern in:
Bitte klicken Sie auf eine der Antwortmöglichkeiten. 

Der Satz sollte ggf. sogar fett sein, meine Frau wusste bei Q1 von Viren nicht, was sie machen soll.
Der erste Satz kann weg.

**Comment by andi-blafasl** [comment]
Alle Quiz-Seiten sind angepasst.

Ich hab auch die "secondary color" geändert. Jetzt sehen die Anworten mehr nach "Knöpfen" aus. Das sollte es intuitiver machen.

**Comment by BITS-Editor** [comment]
Danke! Hätte ich sonst auch gemacht, da warst Du zu schnell :-)
