### ISSUE TITLE
bits-training.de anpassen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#58]
HTML-Version dort hochladen.

**Comment by andi-blafasl** [comment]
oder die Domain auf die GitHub Pages (bits-training.github.io) umstellen :wink:

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

**Comment by BITS-Editor** [comment]
Yo, allerdings habe ich nur Zugriff per FTP auf den Webserver - nix DNS oder Subdomains. 😪

**Comment by andi-blafasl** [comment]
geht da bei IONOS nix? dann Domain umziehen :wink:

**Comment by BITS-Editor** [comment]
Das Hosting läuft über die Kommunalagentur - ich kann mal nachfragen, was da geht. Ich selbst habe eben nur die FTP-Daten.

**Comment by BITS-Editor** [comment]
Habe eben nachgefragt, vielleicht bekommen wir das hin.
