### ISSUE TITLE
Menü-Box in Breadcrumb-Leiste

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#6]
Auf einigen Seiten gibt es ganz oben in der Breadcrum-Leiste ein Menü-Icon, auf anderen nicht. Hat das einen Zweck?

1. Beispiel MIT Icon
https://bits-training.github.io/035-lektion-e-mail/01.was-sind-emails/

2. Beispiel OHNE Icon
https://bits-training.github.io/035-lektion-e-mail/

**Comment by andi-blafasl** [comment]
Das ist eine TOC (Table of Content) die automatisch generiert wird, wenn es sich um eine Seite handelt. Dein Beispiel ohne Diese TOC ist eine "Übersichtsseite" also die oberste Stufe in der Hierarchie. Wenn man die Seiten mit mehr Text befüllt, dann macht die TOC schon schon sinn. Ich denke über die Struktur sollten wir auch noch mal diskutieren.

**Comment by BITS-Editor** [comment]
Ok. Ich mir ist nur aufgefallen, dass oben sich das Aussehen etwas ändert, je nach dem ob das ToC da ist oder nicht.

**Comment by andi-blafasl** [comment]
eventuell abschalten?

**Comment by andi-blafasl** [comment]
Die TOC kann man über den Parameter `disableToc = true` ausschalten. Leider nicht global sondern nur auf der jeweiligen Seite. Müsste man also in alle Seiten einbauen.

**Comment by BITS-Editor** [comment]
Beobachten wir - stört nicht wirklich und ist teilweise sinnvoll. Wenn man die Funktion kennt :-)

**Comment by BITS-Editor** [comment]
Machen wir vielleicht erst mal zu.
