### ISSUE TITLE
Links zu https://getgrav.org/

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#61]
Brauchen wird diesen Link? Lädt der etwas nach bei den statischen Seiten?

**Comment by andi-blafasl** [comment]
Nö, der ist halt im Theme als Werbung drin. Das hat keinen technischen Hintergrund. Kann raus oder durch was eigenes ersetzt werden. -> Datei "\layouts\partials\menu-footer.html"

**Comment by BITS-Editor** [comment]
Passt so, danke.
