### ISSUE TITLE
Start-Seite wird übersprungen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#62]
Der rechte Navigationspfeil führt von der index-Seite auf der obersten Ebene nicht auf die 10 Start-, sondern die 20 Einleitungs-Seite.

**Comment by andi-blafasl** [comment]
Das liegt daran das die Seite 010 Start eigentlich versteckt ist und der Start-Link mit dem schönen Haus per Parameter eingetragen ist. Ich ändere das mal und dann kannst du sagen was dir lieber ist.

**Comment by andi-blafasl** [comment]
Diese Änderung inklusive all deiner fixes sind jetzt auf bits-training.github.io verfügbar.

**Comment by BITS-Editor** [comment]
Danke! Passt!
