### ISSUE TITLE
Titel und Hauptüberschrift der Lektionseiten

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#7]
Ich schlage vor, dass die h1 auf den Lektionsseiten = der Lektionsname ist und nur die h2 die Seitenüberschrift führt.
Beispiel aktuell https://bits-training.github.io/035-lektion-e-mail/04.uebermittlung-von-e-mails-im-internet-2/

Änderung:
Die in Kapitälchen stehenden zentrierten Worte "ÜBERMITTLUNG VON E-MAILS IM INTERNET (2)" (=h1) werden durch "E-Mail" ersetzt. Die Zeile darunter stehende Zeile bleibt (=h2).

**Comment by andi-blafasl** [comment]
Die Zentrierte Überschrift ist der Titel der Seite. Also auch das was links im Menü erscheint. Der H2 kommt aus dem Markdown. Um das zu ändern müssen wir die Vorlage aus dem Theme komplett anpassen.

**Comment by BITS-Editor** [comment]
Verstehe ich - aber wäre das ok für Dich? So haben wir ja zweimal die Überschrift untereinander - und das sieht für mich doof aus.

**Comment by andi-blafasl** [comment]
Doppelt stehen lassen würde ich das definitiv nicht. Ich denke das mit einer anderen Struktur der Inhalte das Problem schöner lösbar ist. Ich bau da mal ein Beispiel in einer anderen Lektion und zeige was ich meine. 

PS: deine Links in den Issues funktionieren alle bei mir nicht. die verweisen immer auf die Issues Seite hier im Repo...

**Comment by BITS-Editor** [comment]
> PS: deine Links in den Issues funktionieren alle bei mir nicht. die verweisen immer auf die Issues Seite hier im Repo...
Sehe ich auch gerade. Merkwürdig.

**Comment by BITS-Editor** [comment]
> Doppelt stehen lassen würde ich das definitiv nicht. Ich denke das mit einer anderen Struktur der Inhalte das Problem schöner lösbar ist. Ich bau da mal ein Beispiel in einer anderen Lektion und zeige was ich meine.

Danke!

**Comment by andi-blafasl** [comment]
So, die Lektion "Passwörter" ist jetzt vom BITS 5.5 übernommen. Die Struktur habe ich etwas abgewandelt. Was haltet ihr von meiner Idee?

**Comment by BITS-Editor** [comment]
Die Idee ist gut - solange die Seiten nicht zu lang werden. Die hier finde ich z.B. etwas zu lang:
https://bits-training.github.io/050-lektion-passwoerter/03.gefahren/
Aber wir können ja selbst entscheiden, was wir zusammenführen - das spart dann auf alle Klickerei. Und natürlich kostbare Bandbreite ;-)

**Comment by BITS-Editor** [comment]
Erinnerung an meine Ausgangs-Idee:
Ich schlage vor, dass die h1 auf den Lektionsseiten = der Lektionsname ist und nur die h2 die Seitenüberschrift führt.
Beispiel aktuell https://bits-training.github.io/035-lektion-e-mail/04.uebermittlung-von-e-mails-im-internet-2/

Änderung:
Die in Kapitälchen stehenden zentrierten Worte "ÜBERMITTLUNG VON E-MAILS IM INTERNET (2)" (=h1) werden durch "E-Mail" ersetzt. Die Zeile darunter stehende Zeile bleibt (=h2).

**Comment by andi-blafasl** [comment]
Das hast du @BITS-Editor ja schon ganz gut im content umgesetzt, oder?
