### ISSUE TITLE
Speicherort Webserver-Version

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#71]
Anscheinend muss die Webserver-Version im Root-Verzeichnis liegen. Das wäre sehr unflexibel.

**Comment by andi-blafasl** [comment]
Ja, die Version funktioniert nur im Root-Verzeichnis. Man kann es ja in eine Sub-Domain legen, dann ist man auch wieder flexibel. Wenn man ein beliebiges Verzeichnis nehmen will, dann muss man auf die "Fileserver" Version setzen, da dort mit relativen Pfaden gearbeitet wird. Die läuft dann, aber hat halt die Einschränkungen. Wenn man den vollen Funktionsumfang haben will, dann passt man die config.toml an und baut sich sein eigenes BITS.
Alternativ können wir auch noch eine weitere Version anbieten, die fest das Verzeichnis "bits" oder so nutzt.

**Comment by BITS-Editor** [comment]
Danke! Noch eine Version sollten wir mE nicht bereitstellen. Aber wir sollten vielleicjt die Doku ergänzen um die Optionen und Wege darzustellen.

**Comment by andi-blafasl** [comment]
Gute Idee mit der Doku!

**Comment by BITS-Editor** [comment]
Entscheidung nach Rücksprache mit dem Initiator des Issues: Wir ändern nur die Doku zu den möglichen Installationspfaden, aber nicht den Code.

**Comment by BITS-Editor** [comment]
Danke! Hier muss ich nur noch redaktionell Kleinigkeiten ändern.

**Comment by BITS-Editor** [comment]
Habe fertig. :-)

**Comment by BITS-Editor** [comment]
Offenbar kann mit der Einstellung relativeURLS=true doch in einem Unterverzeichnis die Webserver-Version ablegen?!?

Siehe hier:
[https://www.rusticus-consulting.de/bits/](https://www.rusticus-consulting.de/bits/)
des neuen GitHub-Contributors @hagen-bauer-rc

**Comment by andi-blafasl** [comment]
Ich weiß, deshalb hab ich die README.md ja auch entsprechend angepasst:
https://github.com/BITS-Training/BITS-hugo/commit/b0bf0821582eac53894b4b6df0732fdcd922c05d#diff-11789ea03ddec94e2c9b9ab8c8e7d60240e17b127025b1ebbfef192a0a58f90d

**Comment by BITS-Editor** [comment]
Sorry, hatte ich vergessen und die Kommentare hier falsch verstanden.
