### ISSUE TITLE
Quiz barrierefrei gestalten mit Tastaturnavigation

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#79]
Das Quiz kann offenbar nur mit der Maus bedient werden. Zur Verbesserung der Barrierefreiheit sollte auch eine Tastaturnavigation möglich sein.

Dazu existiert ein Issue für das Quiz unter https://github.com/bonartm/quizdown-js/issues/15

Die Expand-Funktion, z.B. in /040-lektion-viren/02.typen-von-viren.html ist eine weitere Herausforderung.

**Comment by andi-blafasl** [comment]
Version 0.5.0 oder neuer einbauen: https://github.com/bonartm/quizdown-js/releases/tag/v0.5.0

**Comment by BITS-Editor** [comment]
Super! @andi-blafasl : könntest Du das in einen DEV-Branch zum Testen einbauen?

**Comment by andi-blafasl** [comment]
ist im dev-6.0.3 Branch drin.

**Comment by BITS-Editor** [comment]
Klappt! Allerdings habe ich bei https://github.com/bonartm/quizdown-js/issues/15 noch gefragt, ob der Antwort-Block automatisch beim Seitenaufruf aktiviert sein kann.

In https://github.com/BITS-Training/BITS-hugo/tree/Inhalts-Update habe ich die Bedienhinweise auf der Seite zur Barrierefreiheit ergänzt. Ist das so verständnlich=

**Comment by BITS-Editor** [comment]
Mein Änderungsvorschlag für den automatischen Fokus auf den Antwort-Block, besonders bei allen Folgeseiten zur ersten Quiz-Seite, wird wohl nicht übernommen. Ich habe aber am 23.03.2022 nochmal nachgefragt.

**Comment by BITS-Editor** [comment]
Schon in den früheren Versionen des Relearn Themes, aber auch in 4.1.0 gibt es auf der Ergebnis-Seite des Quiz offenbar keine Möglichkeit, per Tastatur die Fragen auszuwählen und die Links zu aktivieren. Dazu habe ich eine Issue beim Quiz-Repo unter https://github.com/bonartm/quizdown-js/issues/27 eröffnet.

**Comment by BITS-Editor** [comment]
Laut @bonartm ist das ein Bug, siehe https://github.com/bonartm/quizdown-js/issues/27

**Comment by BITS-Editor** [comment]
Wird zurück gestellt, da der Entwickler keine Zeit hat.

**Comment by andi-blafasl** [comment]
Tastaturnavigation läuft grundsätzlich mit version 0.6.0 des quizdown js. Damit schließe ich das issue hier.
