### ISSUE TITLE
Quiz überarbeiten

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#8]
Das neue Quiz ist ja cool! Sogar mit Verschiebe-Aufgaben!
https://bits-training.github.io/035-lektion-e-mail/90.quiz/

**Comment by andi-blafasl** [comment]
Ich habe unter https://bits-training.github.io/050-lektion-passwoerter/05.qiuz/ Den Quiz vom BITS 5.5 testweise komplett übernommen.

**Comment by andi-blafasl** [comment]
Das https://github.com/bonartm/quizdown-js/pull/3 ist auch eine geniale Idee!

**Comment by BITS-Editor** [comment]
> Das [bonartm/quizdown-js#3](https://github.com/bonartm/quizdown-js/pull/3) ist auch eine geniale Idee!

In der Tat!

**Comment by BITS-Editor** [comment]
Wir müssen die Aufgaben und Antworten noch näher betrachten. Z.B. sollten Mehrfach-Antworten nur möglich sein, wo das auch gewollt ist (bislang gar nicht).

Auch müssen wir deutlich auf den "Next"-Button hinweisen, damit die Leute nicht rechts den normalen Navi-Button drücken. Aber das wird klasse!

**Comment by BITS-Editor** [comment]
1. Farbgebung: Lutz passt die Farben an (Schriftfarbe der Fragen geht nicht)
2. Mehrfachauswahl und Hinweis auf die nächste Frage in die Anleitung
3. Zu Sprache der Buttons hat Andreas ein Issue beim Quiz-Repo eingestellt

**Comment by andi-blafasl** [comment]
Single joice geht übrigends über ordered List:
```
1. [x] Kleine Programmteile, die sich unbemerkt an ein anderes Programm anhängen und so auf fremden Rechnern ausgeführt werden können.
2. [ ] Mikroskopisch kleine elektronische Teile, die Computer ausspionieren oder andere zerstörerische Aktionen ausführen.
3. [ ] Schädliche Programme, die jedoch in Ihrer Einrichtung keine Gefahr darstellen, weil sie durch Verschlüsselungssoftware und Virenscanner sofort unschädlich gemacht werden.
4. [ ] Bösartige Krankheitserreger, die in schmutzigen Computersystemen leben.
```
multiple joice über unorderd List:
```
> Vertrauliche Daten dürfen nur verschlüsselt über das Internet verschickt werden.

- [ ] Als E-Mail mit dem klar sichtbaren Vermerk „vertraulich“ in Betreff-Zeile und E-Mail-Text.
- [x] Vertrauliche Daten dürfen nur verschlüsselt über das Internet verschickt werden.
- [ ] Die Daten müssen an den "Vertraulichkeitsbeauftragten" Ihrer Einrichtung geschickt werden, der sie dann verschlüsselt über das Internet weiterleitet.
- [ ] Vertrauliche Daten dürfen von der dienstlichen E-Mail-Adresse aus nur für private Zwecke und als „privat“ gekennzeichnete E-Mail verschickt werden.
```

**Comment by BITS-Editor** [comment]
> Single joice geht übrigends über ordered List:
> 
> ```
> 1. [x] Kleine Programmteile, die sich unbemerkt an ein anderes Programm anhängen und so auf fremden Rechnern ausgeführt werden können.
> 2. [ ] Mikroskopisch kleine elektronische Teile, die Computer ausspionieren oder andere zerstörerische Aktionen ausführen.
> 3. [ ] Schädliche Programme, die jedoch in Ihrer Einrichtung keine Gefahr darstellen, weil sie durch Verschlüsselungssoftware und Virenscanner sofort unschädlich gemacht werden.
> 4. [ ] Bösartige Krankheitserreger, die in schmutzigen Computersystemen leben.
> ```
> 
> multiple joice über unorderd List:
> 
> ```
> > Vertrauliche Daten dürfen nur verschlüsselt über das Internet verschickt werden.
> 
> - [ ] Als E-Mail mit dem klar sichtbaren Vermerk „vertraulich“ in Betreff-Zeile und E-Mail-Text.
> - [x] Vertrauliche Daten dürfen nur verschlüsselt über das Internet verschickt werden.
> - [ ] Die Daten müssen an den "Vertraulichkeitsbeauftragten" Ihrer Einrichtung geschickt werden, der sie dann verschlüsselt über das Internet weiterleitet.
> - [ ] Vertrauliche Daten dürfen von der dienstlichen E-Mail-Adresse aus nur für private Zwecke und als „privat“ gekennzeichnete E-Mail verschickt werden.
> ```

Ha! Ist ja cool! Zwar muss man zum Ändern in den Quellcode-Modus bei Typora wechseln und Handarbeit leisten, aber es klappt. Klasse! Vielen Dank!

**Comment by andi-blafasl** [comment]
und die Kommentare gehen jetzt auch ;-)
```
1. [x] Kleine Programmteile, die sich unbemerkt an ein anderes Programm anhängen und so auf fremden Rechnern ausgeführt werden können. >
    Richtige Antwort!
2. [ ] Mikroskopisch kleine elektronische Teile, die Computer ausspionieren oder andere zerstörerische Aktionen ausführen. >
    Das ist zwar in Entwicklung, aber noch nicht realität ;-)
3. [ ] Schädliche Programme, die jedoch in Ihrer Einrichtung keine Gefahr darstellen, weil sie durch Verschlüsselungssoftware und Virenscanner sofort unschädlich gemacht werden. >
    Schutzprogramme erkennen nur bekannte Bedrohungen! Diese Anwort ist falsch.
4. [ ] Bösartige Krankheitserreger, die in schmutzigen Computersystemen leben. >
    Das wären normale Viren und Bakterien die für den Menschen gefährlich werden könnnen, das ist hier aber nicht gemeint!
```
Wichtig ist, das größer als Zeichen muss am ende der Antwort stehen, die Erklärung mit 4 Leerzeichen in der nächsten Zeile.
Wobei sich diese Syntax noch ändern kann. Im Pull request beschreibt @bonartm das ja entsprechend. Aber so könne wir erst mal damit arbeiten. Die Anpassung ist später dann leicht möglich.

**Comment by andi-blafasl** [comment]
die neue Version vim Quiz.js ist jetzt im main-branch. Eine Frage im e-mail quiz ist angepasst.

**Comment by BITS-Editor** [comment]
Klappt! Klasse! Auch die Sprache der Buttons passt!

Allerdings ist auf der letzten Fragen-Seite "Außwertung" falsch geschrieben (richtig: Auswertung).

**Comment by andi-blafasl** [comment]
So, die neue Version des quizdown.js ist auf der [Testseite](http://localhost:1313/030-lektion-e-mail/90.quiz-e-mails/) auch eingebunden. Ich finde es sieht unglaublich viel besser aus! Die Übersetzung ist jetzt vom Entwickler direkt und ohne meine Schreibfehler :wink:

Leider gibt's wohl noch einen Bug wenn man das Quiz mehrfach durchführt. Da passen beim Ergebnis die Icons nicht. Hab schon ein Issue aufgemacht: https://github.com/bonartm/quizdown-js/issues/7#issue-890950493

**Comment by BITS-Editor** [comment]
Die verlinkte Testseite ist localhost. Soll das so?

**Comment by andi-blafasl** [comment]
Natürlich nicht... sorry :wink:
https://bits-training.github.io/030-lektion-e-mail/90.quiz-e-mails/

**Comment by BITS-Editor** [comment]
Wow! Das ist ein Quantensprung! Schaue ich mich nach Pfingsten näher an. Danke?

**Comment by andi-blafasl** [comment]
Es gab noch einen Bug bei Single-Choice Fragen. Aber Entwickler ist echt auf zack und hat ihn kurz nach meiner Meldung behoben. Die aktuelle Version ist eingepflegt und auf https://bits-training.github.io/ aktiv.

**Comment by andi-blafasl** [comment]
Es gibt gerade ein Problem bei github.com https://github.community/t/unable-to-build-page-please-try-again-later/122613/30
Die Seite wird nicht aktualisiert. Dauert also noch bis meine Änderungen auf https://bits-training.github.io/ sichtbar sind.

**Comment by BITS-Editor** [comment]
In meinem content-update branch, der den translation-test branch beinhaltet, ist noch das alte Layout. Was müssen wir machen, um das neue schicke zu bekommen?
https://bits-training.github.io/030-lektion-e-mail/90.quiz-e-mails/

**Comment by andi-blafasl** [comment]
![image](https://user-images.githubusercontent.com/3586675/120496197-aafee980-c3bd-11eb-8e8f-1df232a28560.png)
wenn ich das richtig sehe, dann hast du die letzten Änderungen im Main-Branch gemacht und nicht im content-update ???
Da bist du wohl irgendwo durcheinander gekommen :wink:

**Comment by BITS-Editor** [comment]
Naja, so halb. Nach meinen letzten Änderungen in den Lektionen habe ich gepusht und dann den Branch content-update gelöscht.

Ist das jetzt ein Problem?

**Comment by BITS-Editor** [comment]
Lutz überarbeitet Quiz bzgl. Syntax der Antworten wie in der E-Mail-Lektion, die bis morgen von Andi gemerged wird.

**Comment by BITS-Editor** [comment]
1. Syntax überarbeitet. Leider gibt einen kleinen Bug: Bei der Ergebnisdarstellung wird bei den richtigen Antworten noch ein Doppelpunkt gesetzt. Kann man den wegbekommen?
2. Readme überarbeitet.

**Comment by andi-blafasl** [comment]
![image](https://user-images.githubusercontent.com/3586675/123428007-9af5b680-d5c5-11eb-9fb5-5a5fb341177f.png)
Ich sehe da überall Doppelpunkte. Was meinst du genau?

**Comment by BITS-Editor** [comment]
Ja. das meinte ich. Und ich sehe jetzt erst, dass da überall Doppelpunkte sind :-)
Ich war aber noch nicht fertig mit dem Fixen. Du hättest hier noch gar nicht gucken sollen!! :-)

**Comment by BITS-Editor** [comment]
So, jetzt fertig. Die Doppelpunkte lassen wir.

**Comment by andi-blafasl** [comment]
Ja, die Doppelpunkte trennen schön die Antwort von der Erklärung. Das ist so schon recht unübersichtlich mit den langen Antworten ;-)
