### ISSUE TITLE
readme und der HowTo-LearnTheme-readme auf neues Theme Relearn anpassen

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#80]
oberste Readme und https://github.com/BITS-Training/BITS-hugo/blob/main/LearnTheme-HowTo.md anpassen, außerdem die index-Seite auf der obersten Ebene und die https://www.bits-training.de/BITS-training-dev/300-infos/herausgeber-und-lizenz/  sowie die static/readme.md

**Comment by andi-blafasl** [comment]
Im Commit https://github.com/BITS-Training/BITS-hugo/commit/27874e03d4829c31a98e59be7abea96721772417 hab ich den Link in der Readme schon angepasst. Die Datei LearnTheme-HowTo können wir doch so lassen, inhaltlich passt die ja auch auf das aktualisierte Theme oder willst du sie umbenennen?

**Comment by BITS-Editor** [comment]
Ich würde schon den neuen Namen des Themes verwenden wollen, ist mE sonst verwirrend. Soll ich einen neuen Branch machen?

**Comment by andi-blafasl** [comment]
Hab sie umbenannt.

**Comment by BITS-Editor** [comment]
Ich habe die weiteren Verweise im Branch Relearn-Umbenennung korrigiert.
