### ISSUE TITLE
Doppelter Zeilenabstand in Auzählungen

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#81]
In der "Achtung"-Box in der [Lektion Internet -> 03. Vertrauens...](https://www.bits-training.de/BITS-training-dev/060-lektion-internet/03.vertrauenswuerdigkeit-von-webseiten/) ist der Zeilenabstand der Aufzählung doppelt.
Ursache ist eine leere Zeile in der .md-Datei. Wenn hier eine Trennung von zwei Listen erzielt werde soll, dann ist es ein Bug im Theme. Das geht nur wenn wen Text zwischen den beiden Aufzählungen steht.

**Comment by andi-blafasl** [comment]
Der Fehler ist mir ebenfalls auf den folgenden Seiten aufgefallen:

https://www.bits-training.de/BITS-training-dev/040-lektion-viren/03.m%C3%B6gliche-sch%C3%A4den-durch-virenbefall/
https://www.bits-training.de/BITS-training-dev/040-lektion-viren/05.risiken-und-schaeden/
https://www.bits-training.de/BITS-training-dev/050-lektion-passwoerter/03.gefahren/
https://www.bits-training.de/BITS-training-dev/060-lektion-internet/02.gefahren-im-internet/
https://www.bits-training.de/BITS-training-dev/070-lektion-vertrauliche-daten/01.vertrauliche-daten/
https://www.bits-training.de/BITS-training-dev/080-lektion-social-media/02.gesch%C3%A4ftsmodell/
https://www.bits-training.de/BITS-training-dev/100-lektion-mobile-geraete/08.mobile-datentraeger/
https://www.bits-training.de/BITS-training-dev/110-lektion-mein-arbeitsplatz/01.sicherer-arbeitsplatz/

**Comment by BITS-Editor** [comment]
Gut erkannt! Danke! Meinetwegen wäre der einfache Zeilenabstand wie hier ausreichend:
https://www.bits-training.de/BITS-training-dev/040-lektion-viren/07.virenbefall-was-tun/

**Comment by andi-blafasl** [comment]
Schau doch bitte die Aufzählung durch und mach die Anpassungen, so wie es dir vom Inhalt und Layout her sinn macht, in einem Branch.

**Comment by BITS-Editor** [comment]
Ok, mache ich.

**Comment by BITS-Editor** [comment]
Erledigt im Branch Zeilenfix
