### ISSUE TITLE
Umlaute in Dateinamen

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#82]
Wir haben Dateien mit Umlauten und ohne (ae/oe/ue Ersatz) im Namen. Wir sollten hier eine einheitliche Vorgehensweise durchsetzen. Mit echten Umlauten könnte es technische Schwierigkeiten geben, deshalb mein Vorschlag: alles umbenennen in die Version ohne Umlaute.

Beispiel:
die URL https://www.bits-training.de/BITS-training-dev/040-lektion-viren/03.m%C3%B6gliche-sch%C3%A4den-durch-virenbefall/ funktioniert bisher ja ohne Probleme, und wird im Browser auch mit schönen Umlauten angezeigt, aber ob das wirklich in allen Situationen so ist, kann ich nicht garantieren.

**Comment by andi-blafasl** [comment]
Hab schon geschaut, sind nur zwei Dateien, das mach ich schnell.

**Comment by BITS-Editor** [comment]
Danke!
