### ISSUE TITLE
Fileserver-Version: Start-Link führt zu Ordner

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#83]
Wenn man in der Fileserver-Version in der Brotkrumen-Navigation auf "Start" klickt, landet man im  Ordner, nicht auf der Startseite.

**Comment by andi-blafasl** [comment]
Hindert uns das jetzt am Release 6.0.1? Oder fixen wir das dann im nächsten Release?

**Comment by BITS-Editor** [comment]
Ist jetzt nicht kritisch, aber ich habe eben beim Testen noch diverse redaktionelle Fehler entdeckt. Ich pushe gleich den neuen Branch.

Ob wir dieses Issue in 6.0.1 fixen hängt vielleicht auch von Aufwand ab, den kann ich nicht abschätzen.

**Comment by andi-blafasl** [comment]
Das Hauptproblem sehe ich hier in unserer "speziellen" Struktur. Die "Startseite" ist ja eine Erklärung was BITS ist und so. Durchaus auch sinnvoll als Landing-Page auf der Homepage [BTIS-Training.de](https://bits-training.de/). Aber für die Verwendung des "installierten" BITS aber total überflüssig.
Ich müsste jetzt in Theme die ganze Breadcrumb-Logic neu schreiben, die ich auf die schnelle erst mal garnicht verstehe 🤷‍♂️ :grin: Zudem steckt die in einer recht großen Datei, die dann komplett unabhängig vom Theme gepflegt werden muss. Das macht es nicht gerade reizvoll...
Vielleicht können wir die Startseite auch mal überdenken und die Struktur entsprechend ändern.

**Comment by andi-blafasl** [comment]
Der Workaround ist jetzt auf der [DEV ](https://bits-training.de/BITS-training-dev)Seite zum testen.

**Comment by andi-blafasl** [comment]
Ich hab mal auf dich schnelle eine "quick and dirty" Landing-Page gebaut: https://www.bits-training.de/landing/

Sowas könnte ich mir als Startseite auf bits-training.de vorstellen. Dann entfernen wir die "Startseite" aus dem BITS-Hugo und stellen die im rechten Link der Landing-Page (natürlich noch optisch aufgehüpscht) zur Verfügung. Und im BITS-Release-Download ist dann die Startseite das was jetzt die 010-start ist.

**Comment by BITS-Editor** [comment]
> Der Workaround ist jetzt auf der [DEV ](https://bits-training.de/BITS-training-dev)Seite zum testen.

Sieht gut aus, das sollte reichen. Danke!

Irgendwann können wir aber auch diese Icons zum Navigieren auf der Seite entfernen. Die sind fast immer leer und zeigen beim MouseOver ein leeres Kästchen.

**Comment by BITS-Editor** [comment]
> Ich hab mal auf dich schnelle eine "quick and dirty" Landing-Page gebaut: https://www.bits-training.de/landing/
> 
> Sowas könnte ich mir als Startseite auf bits-training.de vorstellen. Dann entfernen wir die "Startseite" aus dem BITS-Hugo und stellen die im rechten Link der Landing-Page (natürlich noch optisch aufgehüpscht) zur Verfügung. Und im BITS-Release-Download ist dann die Startseite das was jetzt die 010-start ist.

Sieht klasse aus und die Idee finde ich auch gut! Sollten wir so machen. Brauchen dann noch Impressum und Barrierefreiheit. Ich mache in Repository dazu Issues auf :-)

**Comment by andi-blafasl** [comment]
Die TOC kann man schon jetzt abschalten. Leider nicht global, sondern nur auf der jeweiligen Seite per Parameter (disableTOC) im FrontMatter. Ich mach da einen Pull Request beim McShelby auf, damit das auch global möglich ist.

**Comment by BITS-Editor** [comment]
Danke!

**Comment by BITS-Editor** [comment]
Umsetzung in v6.0.2

**Comment by BITS-Editor** [comment]
Ich sehe gerade, dass im Dev-Branch die Index-Seite ja schon weg ist :-)
