### ISSUE TITLE
Menü zeigt Einträge unter "MEHR" doppelt

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#84]
Wenn man links in der Menüleiste auf einen Eintrag unter "MEHR" klickt, wird dieser dann zusätzlich auch etwas oberhalb in der Menüleiste angezeigt.

**Comment by andi-blafasl** [comment]
Das hab ich auch gesehen, verstehe aber noch nicht genau wo der Bug herkommt. Wenn ich Muße hab, dann mach ich bei McShelby ein Issue auf :wink:

**Comment by BITS-Editor** [comment]
Ok.

**Comment by andi-blafasl** [comment]
https://github.com/McShelby/hugo-theme-relearn/issues/134

**Comment by BITS-Editor** [comment]
Ist wohl im Dev gefixt, oder?
