### ISSUE TITLE
TOC global deaktivieren

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#85]
In version 2.8.0 des ReLearn Themes wird ein feature kommen das mit das deaktivieren global ermöglicht und nicht nur pro Seite. Der [Pull-Request](https://github.com/McShelby/hugo-theme-relearn/pull/132) dazu steht bei McShelby und gefällt ihm 👍

**Comment by BITS-Editor** [comment]
Können wir dieses Issue jetzt schließen?
