### ISSUE TITLE
Eintrag im Showcase des Relearn Themes

### ISSUE THREAD

**Issue by andi-blafasl** [BITS-Training/BITS-hugo#87]
Sollen wir uns von McShelby in den Showcase des Themes aufnehmen lassen?

https://mcshelby.github.io/hugo-theme-relearn/showcase/

**Comment by BITS-Editor** [comment]
Sehr gerne! Hast Du schon einen etablierten Kontakt zu ihm oder soll ich ihn ansprechen?

**Comment by andi-blafasl** [comment]
Ich mach ihm einfach einen Pull-Request für die exampleSite, dann hat er keine Arbeit damit ;-)

**Comment by BITS-Editor** [comment]
Klasse!

**Comment by andi-blafasl** [comment]
https://github.com/McShelby/hugo-theme-relearn/pull/135
mal schauen was er davon hält.

so wird es dann aussehen:
![image](https://user-images.githubusercontent.com/3586675/140068612-99e9efa1-cd42-4b45-8f4a-cb0e3c13877a.png)

**Comment by BITS-Editor** [comment]
Anscheinend sind wir jetzt der einzige Showcase?!?

**Comment by andi-blafasl** [comment]
McShelby hat die anderen rausgeschmissen weil die noch vom alten Learn Theme waren. So steht's zumindest im [commit](https://github.com/McShelby/hugo-theme-relearn/commit/a48824d99195c693d6326ccd73efe5958d333509) 
Vielleicht kommen in Zukunft noch welche dazu, so lange stehe wir halt prominent alleine da 🤣

**Comment by BITS-Editor** [comment]
Danke!
