### ISSUE TITLE
Datenschutzerklärung nicht DSGVO Konform 

### ISSUE THREAD

**Issue by hagen-bauer-rc** [BITS-Training/BITS-hugo#89]
Die Struktur der Webseite erfüllt nicht die Anforderungen der DSGVO wenn man die Schulung auf einem öffentlichen Server betreibt. Die Datenschutzformulierung muss auf einer eigenen Seite enthalten sein und über einen Link von jeder Seite erreichbar sein. 

Mein Vorschlag wäre das man eine neue Seite auf der obersten Ebene erstellt und ein leeres Template für die Datenschutzerklärung bereitstellt. Dieser Seite sollte die Anwender auffordern hier eine saubere Datenschutzerklärung einzufügen.

**Comment by hagen-bauer-rc** [comment]
Also es gibt einige öffentliche Instanzen von BITS. Angefangen mit https://www.bits-training.de/training/index.html. Auch die ist nicht DSGVO Konform

**Comment by BITS-Editor** [comment]
Danke für die Hinweise. To-Dos wären nach Prüfung:
1. Umbenennung der Menü-Überschrift "Herausgeber und Lizenz" in "Datenschutz und Lizenz"
2. Ergänzung der Datenschutzhinweise um Inhalte aus [Art. 13 DSGVO](https://dsgvo-gesetz.de/art-13-dsgvo/)

**Comment by BITS-Editor** [comment]
Änderungsvorschlag im Branch
https://github.com/BITS-Training/BITS-hugo/tree/Datenschutz-Tuning

**Comment by BITS-Editor** [comment]
Die Landing-Page muss noch angepasst werden. Rechts oben muss "Impressum" durch "Datenschutz und Lizenz" ersetzt und der Link angepasst werde.

**Comment by BITS-Editor** [comment]
Für den Betrieb von BITS-Training(.de) zumindest für die öffentliche Hand ist mE Art. 6 Abs. 1 Satz 1 lit e) DSGVO korrekt, da dies im öffentlichen Interesse ist.

**Comment by BITS-Editor** [comment]
Das Problem ist etwas größer. Das Hosting von www.bits-training.de läuft unter github.io. Von dort wird auf die Regeln von github.com verwiesen. Diese Regeln erscheinen mir nicht DSGVO-konform. Anscheinend wird endlos gespeichert, nur bei Löschbegehren wird 30 Tage später gelöscht. Immerhin werden bei github.io keine Cookies gesetzt.

[Dort ](https://docs.github.com/en/github/site-policy/github-privacy-statement)heißt es:
GitHub Pages
If you create a GitHub Pages website, it is your responsibility to post a privacy statement that accurately describes how you collect, use, and share personal information and other visitor information, and how you comply with applicable data privacy laws, rules, and regulations. Please note that GitHub may collect User Personal Information from visitors to your GitHub Pages website, including logs of visitor IP addresses, to comply with legal obligations, and to maintain the security and integrity of the Website and the Service.

Das müssten wir im Team mal besprechen.

**Comment by hagen-bauer-rc** [comment]
Wenn es hilft könnte ich die Seite hosten. IPs werden im Nginx anonymisiert. (Ich gehe davon aus das die Serverlast überschaubar ist.

**Comment by BITS-Editor** [comment]
Vielen Dank! Wir prüfen derzeit noch andere Optionen, ggf. kommen wir auf das freundlichen Angebot zurück :-)

**Comment by andi-blafasl** [comment]
Ich würde vorschlagen wir bauen in die Landing-Page ein eigenes Impressum und eine Datenschutzerklärung ein.
Im Bits machen wir zwei neue Seite "Datenschutz" und "Impressum" die als Template bereitgestellt werden und die jeder Betreiber selbst anpassen muss. 
Den Punkt Herausgeber und Lizenz würde ich soweit anpassen das hier nichts mehr mit Datenschutz und Impressum enthalten ist. Wir betreiben ja keine öffentliche Instanz von BITS, sonder zeigen nur eine Demo unseres "Produktes"

Zum Thema GitHub Pages würde ich dann in der Landing-Page soetwas vorschlagen: https://opr.vc/docs/hosting/github_pages/

Eine Umstellung auf ein "normales" Hosting mit irgendwelchen halbautomatischen, zeitlich versetzten, geskripteten oder sonst irgendwelchen Bastellösungen finde ich nicht gut.
Wir sind keine Firma oder sonst was und wir betreiben auch kein Business damit.

**Comment by hagen-bauer-rc** [comment]
@andi-blafasl ich weiss nicht  wie ich es schöner oder freundlicher ausdrücken kann. Aber die Aussage

**Comment by andi-blafasl** [comment]
@hagen-bauer-rc ich sage nicht, das wir keine brauche. Aber wir nutzen einfach GitHub als unseren Hoster und da wir keine Firma sind, benötigen wir nach meinem Verständnis dann keinen AVV. Es werden keine personenbezogenen Daten (außer der IP-Adresse, was für ein Blödsinn...) Erfasst und keine Cookies gesetzt. Würden wir das Hosting bei dir machen, dann wärst ja auch du ein Dritter, also gleiches Problem.

Wenn jemand auf unsere Online-Demo verweist, dann ist er ja dafür verantwortlich. Ich baue gerade die Landing-Page entsprechend um, damit hier Impressum und Datenschutz entsprechend erklärt werden.

Im BITS selbst gibt's dann nur noch ein Template, das jeder selbst befüllen muss.

**Comment by BITS-Editor** [comment]
Ich habe mir die Sachen endlich mal mit etwas zeitlicher Distanz angeguckt und sehe folgende Situation:
1. Für die Landing Page brauchen wir Impressum und DS-Erklärung, da sind wir uns einig. Laut BayLDA benötigen wir KEINEN Auftragsverarbeitungsvertrag.
2. Für die BITS-Demo gilt mE das Gleiche. ABER: ich unterstütze Andreas' Anregung, hier zwei Templates zu bauen. Dort würde ich dann mit Parametern arbeiten oder in der Readme auf die zu ändernden Inhalte hinweisen.

Ich habe im Branch Datenschutz-Tuning einen Vorschlag inkl. der hier https://github.com/BITS-Training/BITS-hugo/issues/89#issuecomment-1002200055 von Andreas verlinkten GitHub-Datenschutzerklärung für die Datenschutzerklärung erstellt. Wenn wir wie von mir vorgeschlagen vorgehen, könnten wir sie für 1. verwenden. Für 2. wäre sie auch verwendbar, aber eben als Template - und dazu noch ein Template für das Impresseum.

Was haltet Ihr davon?

**Comment by hagen-bauer-rc** [comment]
Ich finde die Idee gut. Inhaltlich habe ich mit der verlinkten Github Datenschutzerklärung meine Bauchschmerzen aber ist halt so bei rechtlichen Fragen und sollte keine Showstopper für eine solche Umsetzung sein. Solange der erwähnte Datenschutzbeauftragte eingebunden ist und das abgenickt hat.

**Comment by andi-blafasl** [comment]
Ich habe jetzt im BITS-hugo Repo einen Branch [Impressum-Vorlage](https://github.com/BITS-Training/BITS-hugo/tree/Impressum-Vorlage) gemacht. @BITS-Editor bitte check das mal, ich hab das schon vor deiner Anpassung lokal gemacht, aber nicht veröffentlich.
Zudem gibt es im bits-training.de Repo einen Branch [Impressum](https://github.com/BITS-Training/bits-training.de/tree/impressum) mit entsprechenden Anpassungen. @BITS-Editor bitte auch den mal anschauen und feedback :wink:

**Comment by BITS-Editor** [comment]
Wir arbeiten an einer Lösung mit Hosting bei der Kommunal Agentur NRW.

**Comment by andi-blafasl** [comment]
Wird mit dem nächsten Release umgesetzt.

**Comment by BITS-Editor** [comment]
Wir müssen noch die DS-Erklärung im bits-training.de-Repo anpassen.

**Comment by BITS-Editor** [comment]
Ist angepasst und geht in Kürze online. Danke nochmal an @hagen-bauer-rc für die wertvollen Hinweise!
