### ISSUE TITLE
Inhalt: Handlungsempfehlung zu Metadaten in Office-Dokumenten

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#90]
Ggf. in Inhalte aufnehmen aus APP.1,1.A09:
Office-Dokumente können in der Regel um eine Vielzahl an Meta-Informationen angereichert werden. Diese umfassen beispielsweise Angaben zum Autor, zur letzten Freigabe oder zur Version des Dokuments. Sie können aber auch schützenswerte Informationen enthalten. Bei der Veröffentlichung von Office-Dokumenten oder der Weitergabe an Dritte ist es daher erforderlich, nicht erwünschte Restinformationen zu entfernen.

Es sollte genau überlegt werden, welche Metadaten die Datei enthalten soll. Hier kann es beispielsweise erwünscht sein, einer Datei eine Vielzahl von Metadaten mitzugeben, damit diese über Suchmaschinen gefunden werden kann. Es kann aber auch sinnvoll sein, keine Metadaten weiterzugeben. Beispielsweise sollte der Name des Autors entfernt werden, wenn ein Dokument anonymisiert weitergegeben werden soll.

Hier ist es sinnvoll, den Benutzern eine Checkliste an die Hand zu geben, die ihnen ermöglicht, unerwünschte Restinformationen zu identifizieren und nach einem definierten Prozess zu löschen.

Beispielhafte Checkliste:

Eingebettete Dokumente entfernenPrüfen, ob in dem Office-Dokument weitere Dokumente als Objekte eingebettet sind. Eingebettete Dokumente sollten entfernt, als Anlage referenziert werden und gegebenfalls als eigenes Dokument mitgeliefert werden.   
Überarbeitungs-Informationen entfernenText, der im Änderungen-Nachverfolgen-Modus eingefügt wurde, sollte entweder akzeptiert werden oder verworfen werden. Die Änderungsinformationen selbst dürfen nicht in veröffentlichten Dokumenten enthalten sein.   
Kommentare entfernenKommentare im Text müssen vor der Veröffentlichung von Dokumenten entfernt werden.   
Überflüssige Dokumenteneigenschaften entfernenIn der Regel sind nur die Dokumenteneigenschaften Autor, Titel, Version und Datum relevant. Die restlichen Dokumenteneigenschaften sollten vor der Veröffentlichung entfernt werden.   
Auf nicht-sichtbaren Inhalt prüfenAbschließend sollte das Dokument auf Inhalte geprüft werden, die nicht sichtbar sind. Das können beispielsweise ausgeblendete Tabellenspalten, Textpassagen, die von einem Bild verdeckt werden oder auch Text in derselben Farbe wie der Hintergrund sein.   

Viele Office-Produkte bieten Funktionen, mit denen die Prüfung auf Restinformationen weitestgehend automatisiert erfolgen kann oder in gewissem Umfang vor vorhandenen Restinformationen gewarnt wird. Für speziellere Überprüfungen kann auch auf Zusatzsoftware oder Eigenentwicklungen zurückgegriffen werden.

Beispielsweise können in LibreOffice Warnungen zu Restinformation in Dokumenten aktiviert werden. Die Einstellungen hierzu sind zu finden unter Extras | Optionen | LibreOffice | Sicherheit | Sicherheitsoptionen und -warnungen.

In Microsoft Office können Warnungen zu Restinformationen im Sicherheitscenter aktiviert werden. Optionen hierzu sind unter Datei | Optionen | Sicherheitscenter | Einstellungen für das Sicherheitscenter zu finden. Hier können Warnungen unter Datenschutzoptionen im Bereich Dokumentspezifische Einstellungen aktiviert werden. Außerdem stellt Microsoft Office eine Prüffunktion bereit. Diese kann unter Datei | Informationen | Auf Probleme überprüfen | Dokument prüfen durchgeführt werden. Bei der Prüffunktion werden bestimmte Restinformationen im Dokument automatisch geprüft und in einem Bericht angezeigt, der gleichzeitig Optionen zum Bereinigen bietet. Bei der Prüffunktion sollte definiert werden, welche Prüfungen sinnvoll sind und welche Bereinigungen durchgeführt werden können.

Häufig sollen in einem Dokument vor dessen Veröffentlichung zudem einzelne Passagen unkenntlich gemacht werden. Abhängig vom Dateiformat sind geeignete Methoden zu ergreifen. Eine beliebte, aber extrem fehlerträchtige Methode ist es, Textpassagen elektronisch zu "schwärzen". Die so übermalten Informationen sind allerdings in vielen Fällen einfach auslesbar. Daher ist dies unbedingt zu unterlassen.

Ein weiteres Beispiel für mögliche Restinformationen ist OLE (Object Linking And Embedding, Dienst zum Verknüpfen und Einbetten von Objekten). Über OLE-Funktionen können Objekte in Dateien eingebettet werden. Diese werden in vielen Office-Produkten benutzt, um Informationen anderen Programmen zur Verfügung zu stellen. Hierüber kann beispielsweise eine in Excel erstellte Tabelle in einem Word-Dokument eingebettet werden. Damit werden aber nicht nur die in dem Tabellenausschnitt dargestellte Informationen, sondern unter Umständen alle in der Excel-Datei enthaltenen Informationen in die Word-Datei übertragen. Wenn die Word-Datei dann weitergegeben wird, kann der Empfänger dann auch die Excel-Datei einsehen und sogar verändern, auch wenn diese durch ein Passwort lese- oder schreibgeschützt war. Um dies zu verhindern, sollte in diesem Beispiel die Tabelle als Text in die Word-Datei kopiert werden. Nur wenn die Ursprungs-Excel-Datei keine anderen Informationen enthält, als solche, die weitergegeben werden sollen, sollte sie in einer andere Datei eingebettet werden. Dies kann z. B. durch Anlegen einer neuen Excel-Datei erreicht werden."

**Comment by BITS-Editor** [comment]
Ich mache mal einen Vorschlag in einem neuen DEV-Branch.

**Comment by BITS-Editor** [comment]
Unter https://github.com/BITS-Training/BITS-hugo/tree/Inhalts-Update habe ich die Seiten https://github.com/BITS-Training/BITS-hugo/blob/Inhalts-Update/content/070%20lektion%20vertrauliche%20daten/02.Elektronische-Datenverarbeitung.de.md und https://github.com/BITS-Training/BITS-hugo/blob/Inhalts-Update/content/070%20lektion%20vertrauliche%20daten/09.Zusammenfassung.de.md entsprechend ergänzt.

**Comment by BITS-Editor** [comment]
@andi-blafasl Ist das verständlich?

**Comment by andi-blafasl** [comment]
ist im dev-6.0.3 eingebaut.
