### ISSUE TITLE
Inhalt: Erweiterung Gefahren aus scheinbar internen Instant Messaging Diensten

### ISSUE THREAD

**Issue by hagen-bauer-rc** [BITS-Training/BITS-hugo#92]
Ursprung der Idee:  Auch Instant-Messaging-Dienste wie Slack werden genutzt um Cyberangriffe einzuleiten. https://securityintelligence.com/posts/nation-state-threat-group-targets-airline-aclip-backdoor/

Ich denke das passt am  besten als weiter Bulletpunkt in 040-lektion-viren/04.infektionswege/

**Comment by BITS-Editor** [comment]
Der Link funktioniert nicht.

Grundsätzlich: Ist das wirklich ein verbreiteter Vektor? In den meisten Behörden gibt es keine zugelassenen Messenger-Dienste.

**Comment by hagen-bauer-rc** [comment]
hier ein anderer https://malware.news/t/nation-state-threat-group-targets-airline-with-aclip-backdoor/55525

Das ist ein neuer Angriffsvektor der an Bedeutung zunehmen wird. Insbesondere wenn wir die wachsende Nutzung des Matrix Protokolls beobachten https://www.chatcloud.net/de/matrix-schleswig-holstein/ Desweiteren steht in der Einleitung ja auch das es um die Beschäftigten von Behörden und Einrichtungen, die sich auch über die private sichere Nutzung von Computer und Internet informieren wollen.

**Comment by BITS-Editor** [comment]
Ich habe leider nicht verstanden, wie der Angriff funktioniert bzw. wie wir hier sensibilisieren können. Ich würde mich über einen Textvorschlag sehr freuen!

Ich habe noch das hier gefunden: https://www.forbes.com/sites/zakdoffman/2021/04/22/forget-whatsapp-new-telegram-warning-for-millions-of-windows-10-users/ Dort ist aber nicht der Messenger selbst das Problem, sondern maliziöse E-Mails und die Telegram-Infrastruktur im Hintergrund.

**Comment by hagen-bauer-rc** [comment]
Ich schreib das einfach mal hier rein für die Diskussion. Ich würde da in ein neues Kapitel unter "Lektion Mein Arbeitsplatz" einfügen 

..........................
 Computerviren per Instant Messenger

Viele Behörden oder Einrichtungen verwenden Messenger Dienste wie Slack, MS Teams, Matrix. Für den Anwender stellen diese Dienste eine vertrauliche Umgebung für die interne Kommunikation   da.

Aber auch auf diesem Wege können Angreifer schadhafte Links oder Downloads bereitstellen.  Nach einem erfolgreichen Eindringen in das Netzwerk versuchen die Angreifer Benutzerinformationen zu erbeuten und nutzen diese dann um unter deren Namen schadhafte Links in die Plattformen einzustellen.
 

 Achtung
Daher sollten Sie:
-  Links und Dateianhängen auch in internen Foren oder Arbeitsbereich nicht blind vertrauen,
-  grundsätzlich keine unbekannten oder merkwürdig erscheinenden Links öffnen,
- keine Dokumente und Programme von bekannten Absendern öffnen, die Ihnen verdächtig oder überraschend erscheinen

**Comment by BITS-Editor** [comment]
@hagen-bauer-rc : Vielen Dank! Ich habe im Branch https://github.com/BITS-Training/BITS-hugo/tree/Inhalts-Update eine neue Seite im Kapitel "Am Arbeitsplatz" eingefügt. Ich hoffe, das passt so. Lustiger Fact: im obigen Vorschlag steht, man solle Links und Dateianhängen nicht "blind" vertrauen siehe Pull-Request #94 ;-)

**Comment by hagen-bauer-rc** [comment]
ja, da hat sich etwas überschnitten

**Comment by BITS-Editor** [comment]
Können wir meinen Vorschlag so lassen?

**Comment by hagen-bauer-rc** [comment]
ich finde das gut

**Comment by BITS-Editor** [comment]
Danke! Dann mache ich hier zu :-)
