### ISSUE TITLE
Löschung "BITS |" aus Parameter "BITS_Titel"

### ISSUE THREAD

**Issue by BITS-Editor** [BITS-Training/BITS-hugo#93]
Ich rege an, in https://github.com/BITS-Training/BITS-hugo/blob/dev-6.0.3/config/_default/config.toml aus dem Parameter "BITS_Titel" den String "BITS |" zu löschen. Sonst taucht "BITS" zu häufig auf.

Dann wäre auch die Überschrift "Ziele des" unter https://github.com/BITS-Training/BITS-hugo/blob/dev-6.0.3/content/020%20einleitung/_index.de.md anzupassen.

**Comment by andi-blafasl** [comment]
ist im dev-6.0.3 angepasst

**Comment by BITS-Editor** [comment]
Danke! Im neuen Branch https://github.com/BITS-Training/BITS-hugo/tree/Inhalts-Update ist auch die Einleitungsseite angepasst. Kann dann hier geschlossen werden.
